### ISSUE TITLE
function to skip header line even though `has_header(false)` (necessary for deserializing structs)

### ISSUE THREAD

**Issue by dlaehnemann** [BurntSushi/rust-csv#101]
To be able to deserialize structs, `csv` currently requires `has_header(false)` to be set for the `ReaderBuilder` and there is no `csv`-native way to still skip the header, anyways. This would be a nice addition, as it otherwise leads to extra `Iterator` code as in the code example of issue #100.

**Comment by BurntSushi** [comment]
I don't understand your question. Firstly, deserialization works with
headers enabled or not. Secondly, skipping the header row is the same as
soipping one item in iterator. Why can't you do that?

**Comment by dlaehnemann** [comment]
Ok, I see that without the `String` in the tuple `(String, EasyStruct)` the deserialization works no matter if `has_headers(false)` is set or not (both with just the `EasyStruct` and with the `EasyStruct` in a Tuple: `(EasyStruct)`). So it is not as general as I though and the following block of code runs fine:
```
#[macro_use]
extern crate serde_derive;
extern crate csv;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
struct EasyStruct {
    primitive_1: u8,
    primitive_2: String
}

fn example1() {
    let easy_struct = "\
primitive_1,primitive_2
42,1
42,Another
";
    let mut reader = csv::ReaderBuilder::new().from_reader(easy_struct.as_bytes());
    let unwrapped = reader.deserialize().collect::<Result<Vec<(EasyStruct)>, _>>().unwrap();

    let es_1 = EasyStruct { primitive_1: 42, primitive_2: String::from("1") };
    let es_2 = EasyStruct { primitive_1: 42, primitive_2: String::from("Another") };
    assert_eq!(unwrapped, vec![
        (es_1),
        (es_2) ] );
}

fn main() {
    example1();
}
```

However, once I add in the `String` into the Tuple (`(String, EasyStruct)`, a setup we have, where more than just the struct is recorded in the csv file), I have to add `has_headers(false)` to the `ReaderBuilder` and `skip(1)` after the `deserialize()` to make it run, like this:
```
#[macro_use]
extern crate serde_derive;
extern crate csv;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
struct EasyStruct {
    primitive_1: u8,
    primitive_2: String
}

fn example1() {
    let easy_struct = "\
string,primitive_1,primitive_2
string_x,42,1
string_y,42,Another
";
    let mut reader = csv::ReaderBuilder::new().has_headers(false).from_reader(easy_struct.as_bytes());
    let unwrapped = reader.deserialize().skip(1).collect::<Result<Vec<(String, EasyStruct)>, _>>().unwrap();

    let es_1 = EasyStruct { primitive_1: 42, primitive_2: String::from("1") };
    let es_2 = EasyStruct { primitive_1: 42, primitive_2: String::from("Another") };
    assert_eq!(unwrapped, vec![
        (String::from("string_x"), es_1),
        (String::from("string_y"), es_2) ] );
}

fn main() {
    example1();
}
```
Otherwise it will fail with the following awkward error, of which I don't understand where it comes from:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Deserialize { pos: Some(Position { byte: 31, line: 2, record: 1 }), err: DeserializeError { field: None, kind: UnexpectedEndOfRow } })', /checkout/src/libcore/result.rs:906:4
```

**Comment by BurntSushi** [comment]
I'm on mobile, but have you carefully read the docs on deserialization on
docs.rs/csv? I am pretty sure the answers to your questions are there. For
example, I feel like you are missing a key consequence of toggling headers.
Namely, if headers are enabled then struct field names are matched with
header fields to do deserialization. Without headers, deserialization in
structs is position based. When headers are enabled, nesting structs aren't
really supported because it isn't clear what the right behavior should be.

It sounds like what you want is to keep headers enabled, but choose a type
that isn't a tuple.

On Jan 10, 2018 12:07, "David Laehnemann" <notifications@github.com> wrote:

Ok, I see that without the String in the tuple (String, EasyStruct) the
deserialization works no matter if has_headers(false) is set or not (both
with just the EasyStruct and with the EasyStruct in a Tuple: (EasyStruct)).
So it is not as general as I though and the following block of code runs
fine:

#[macro_use]
extern crate serde_derive;
extern crate csv;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
struct EasyStruct {
    primitive_1: u8,
    primitive_2: String
}

fn example1() {
    let easy_struct = "\
primitive_1,primitive_2
42,1
42,Another
";
    let mut reader =
csv::ReaderBuilder::new().from_reader(easy_struct.as_bytes());
    let unwrapped =
reader.deserialize().collect::<Result<Vec<(EasyStruct)>,
_>>().unwrap();

    let es_1 = EasyStruct { primitive_1: 42, primitive_2: String::from("1") };
    let es_2 = EasyStruct { primitive_1: 42, primitive_2:
String::from("Another") };
    assert_eq!(unwrapped, vec![
        (es_1),
        (es_2) ] );
}

fn main() {
    example1();
}

However, once I add in the String into the Tuple ((String, EasyStruct), a
setup we have, where more than just the struct is recorded in the csv
file), I have to add has_headers(false) to the ReaderBuilder and skip(1)
after the deserialize() to make it run, like this:

#[macro_use]
extern crate serde_derive;
extern crate csv;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
struct EasyStruct {
    primitive_1: u8,
    primitive_2: String
}

fn example1() {
    let easy_struct = "\
string,primitive_1,primitive_2
string_x,42,1
string_y,42,Another
";
    let mut reader =
csv::ReaderBuilder::new().has_headers(false).from_reader(easy_struct.as_bytes());
    let unwrapped =
reader.deserialize().skip(1).collect::<Result<Vec<(String,
EasyStruct)>, _>>().unwrap();

    let es_1 = EasyStruct { primitive_1: 42, primitive_2: String::from("1") };
    let es_2 = EasyStruct { primitive_1: 42, primitive_2:
String::from("Another") };
    assert_eq!(unwrapped, vec![
        (String::from("string_x"), es_1),
        (String::from("string_y"), es_2) ] );
}

fn main() {
    example1();
}

Otherwise it will fail with the following awkward error, of which I don't
understand where it comes from:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: Error(Deserialize { pos: Some(Position { byte: 31, line: 2,
record: 1 }), err: DeserializeError { field: None, kind:
UnexpectedEndOfRow } })', /checkout/src/libcore/result.rs:906:4

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/BurntSushi/rust-csv/issues/101#issuecomment-356668643>,
or mute the thread

**Comment by dlaehnemann** [comment]
I did do quite a bunch of reading and checking code versions, but I think I also got confounded by some of what I reported in Issue #101. However, what we would want is for the following to work with automatic nested matching of the header line entries to the `EasyStruct` entries:
```
#[macro_use]
extern crate serde_derive;
extern crate csv;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
struct EasyStruct {
    primitive_1: u8,
    primitive_2: String
}

fn example1() {
    let easy_struct = "\
string,primitive_1,primitive_2
string_x,42,1
string_y,42,Another
";
    let mut reader = csv::ReaderBuilder::new().from_reader(easy_struct.as_bytes());
    let unwrapped = reader.deserialize().collect::<Result<Vec<(String, EasyStruct)>, _>>().unwrap();

    let t_1 = ( String::from("string_x"),
                EasyStruct {
                    primitive_1: 42,
                    primitive_2: String::from("1")
                } );
    let t_2 = ( String::from("string_y"),
                EasyStruct {
                    primitive_1: 42,
                    primitive_2: String::from("Another")
                } );
    assert_eq!(unwrapped, vec![t_1, t_2] );

}

fn main() {
    example1();
}
```

We had code that worked with such a `.collect()` into a Tuple mixing primitives with a struct with the `decode()` function in `csv` `0.15.0` and were trying to replicate that behaviour with `deserialize()` in the latest `csv` beta version.

**Comment by BurntSushi** [comment]
You can either have positional mapping with nested product types or you can have one struct with name matching. You can reproduce 0.15 behavior by disabling headers and writing skip(1) in your iterator.

**Comment by dlaehnemann** [comment]
In any case, thanks for digging into this with me! :)

**Comment by BurntSushi** [comment]
No problem. Also, I should say, the failure modes here aren't great. I'd welcome ideas (especially implementation strategies with respect to Serde) on how to improve them!
