### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by heinrich5991** [BurntSushi/rust-csv#105]
Could you release the 1.0.0 version? What's still missing?

**Comment by BurntSushi** [comment]
I have a lot on my plate, so I can't always stay on top of every library I maintain. It will happen when it happens.

Looking through the issue tracker, one issue that gives me pause is #93. In particular, the serialization side of that has been done but the deserialization side hasn't been. (cc @jturner314) I don't mind punting on the deserialization half until after 1.0, but I need to make sure it won't introduce any breaking changes. That requires someone thinking through it.

**Comment by jturner314** [comment]
I took a look at implementing the deserializer for containers of structs and added some comments to #93. Personally, I think it would be a good idea to implement this before stabilization, because, even though I don't expect there to be any breaking changes, in the past I've found breaking changes hard-to-predict without actually writing the implementation.

**Comment by heinrich5991** [comment]
Implementing https://github.com/serde-rs/serde/issues/119 would fix the issue for all de-/serializers.

**Comment by BurntSushi** [comment]
I'm going to move forward with the 1.0 release. It doesn't make sense to block it on support for nested deserialization. Unfortunately, serde's new `flatten` feature doesn't appear to work out of the box and it's not obvious why.

**Comment by BurntSushi** [comment]
csv 1.0 is on crates.io.
