### ISSUE TITLE
csv::Reader::from_string gone in version 1

### ISSUE THREAD

**Issue by marvinvperez** [BurntSushi/rust-csv#112]
Hi @BurntSushi , I upgrade csv version to 1 but the function from_string in Reader is gone? Code below gives me error

`136 |     let mut rdr = csv::Reader::from_string(String::from_utf8_lossy(bytes)).has_headers(true);
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `csv::Reader<_>``

Can you look?

**Comment by BurntSushi** [comment]
The `from_string` method no longer exists because it is subsumed by the `from_reader` method. Namely, `&[u8]` implements `io::Read`, so you if you have a `&str`, you can get a `io::Read` by calling `as_bytes`.

A significant portion of the examples use this approach. Here's one: https://docs.rs/csv/1.0.0/csv/struct.Reader.html#method.from_reader

**Comment by Niedzwiedzw** [comment]
might be worth putting it in the docs
