### ISSUE TITLE
Performance Problems

### ISSUE THREAD

**Issue by soaxelbrooke** [BurntSushi/rust-csv#116]
Howdy!  I am seeing performance problems in my use of the lib, but from what I can tell I am using it in the proper way.  See below code that simply reads the first 1000 lines of a CSV and counts them:

```rust
extern crate csv;

fn main() {
    let mut reader = csv::ReaderBuilder::new()
        .delimiter(b' ')
        .from_path("./data/glove/glove.twitter.27B.25d.txt")
        .expect("oops");
    println!("{}", reader.records().take(1000).count());
}
```

This takes about 30 seconds wall clock time, which is ludicrously slow - I assume I am doing something wrong, but I'm at a loss as to what that might be.

PS, you can find the mentioned GloVe files [here](https://nlp.stanford.edu/projects/glove/).

Thanks!

**Comment by BurntSushi** [comment]
Thanks for the report. You need to share how you're building your code. Most pertinently, did you compile with `--release`?

**Comment by soaxelbrooke** [comment]
For context:

```bash
$ time target/release/csv-read-example
1000

real    0m32.112s
user    0m11.641s
sys     0m20.470s
```

And using `wc` for posterity:

```bash
$ time head -1000 data/glove/glove.twitter.27B.25d.txt | wc -l
1000

real    0m0.004s
user    0m0.001s
sys     0m0.006s
```

**Comment by soaxelbrooke** [comment]
I'm building with `cargo build --release`.

**Comment by BurntSushi** [comment]
Something definitely looks off here. Unfortunately I'm headed out for vacation for a couple days and won't be able to look at this.

**Comment by BurntSushi** [comment]
@soaxelbrooke Now that I've had time to look at this in a less rushed state while packing for vacation, the problem jumped out at me immediately: your CSV data is more like "space delimited" data, and doesn't seem to use quoting at all. But the default CSV reader assumes that quoting is done. The 13th record in your data starts itself with a `"`, which the CSV readers interprets as "begin a field and don't end it until another `"` is seen." This then causes the CSV reader to create a *very large* field, because the next `"` doesn't begin until record 216,342. Which in turn begins another large field. And this chain continues and causes performance to degrade and memory usage to increase.

I wish there were a better failure mode here, but I'm not really seeing how it could be done. In general, you really need to examine your data closely and debug how it's being parsed by the reader. In this case, you had a single field that was megabytes large---that has to tip you off that something has gone wrong.

In any case, this program now works. Namely, the [`quoting`](https://docs.rs/csv/1.0.0/csv/struct.ReaderBuilder.html#method.quoting) method lets you disable quoting completely. Your data also doesn't have headers, which are enabled by default, which in turn means your program was silently skipping the first record (since it was interpreted as headers). You can disable headers with the [`has_headers`](https://docs.rs/csv/1.0.0/csv/struct.ReaderBuilder.html#method.has_headers) method.

```rust
extern crate csv;

fn main() {
    let mut reader = csv::ReaderBuilder::new()
        .delimiter(b' ')
        .has_headers(false)
        .quoting(false)
        .from_path("./glove.twitter.27B.25d.txt")
        .expect("oops");
    println!("{}", reader.records().take(1000).count());
}
```

**Comment by sbstp** [comment]
I just ran into this issue as well. I was reading the `titles.akas.tsv' of imdb and the reading slowed down to a crawl, turning off quoting fixed the issue. It might be worth adding to a FAQ.
