### ISSUE TITLE
A way to assert headers

### ISSUE THREAD

**Issue by yongqli** [BurntSushi/rust-csv#118]
I have a csv file with a very non-standard header [1]. It would be nice to have a way to assert that the header is what I'm expecting by providing a `&str` without attempting to parse the header. In my particular use case a way to skip extra headers at the end would solve my problem as well.

[1] The header ends with `,num_structs,{field1,field2}[num_structs]` -- I'm guessing it is hopeless to try to get any CSV parser to understand it...

**Comment by BurntSushi** [comment]
Could you please provide a complete example, with source code, input and the desired output? Otherwise, I don't really understand what it is you're asking for. I also don't know what it is you've tried. For examples, have you tried using the [`headers`](https://docs.rs/csv/1.0.0/csv/struct.Reader.html#method.headers) method to get a [`StringRecord`](https://docs.rs/csv/1.0.0/csv/struct.StringRecord.html) containing your headers? If you have a `StringRecord`, then you can do things like call its [`as_slice`](https://docs.rs/csv/1.0.0/csv/struct.StringRecord.html#method.as_slice) method to get a single contiguous `&str` with all of the fields stitched together.

**Comment by yongqli** [comment]
Thanks -- I missed `as_slice()` -- I guess I was looking for `as_str()` or something.
