### ISSUE TITLE
Strict parsing with Serde

### ISSUE THREAD

**Issue by jbcden** [BurntSushi/rust-csv#125]
I was testing out some ideas on the Serde example from the README and was a bit surprised at some of the results. For this issue I will be referring to the `Record` struct:
```rust
#[derive(Debug, Deserialize)]
struct Record {
    city: String,
    region: String,
    country: String,
    population: Option<u64>,
}
```
The thing that surprised me is that if a non-optional field, say "city", is left blank in the CSV then
```rust
let record: Record = result?;
```
results in the record being parsed without an error and the "city" field being parsed as `""`. I might be missing an attribute I could assign but I was hoping to make this case an error instead of parsing fine. Is this possible without creating a custom deserializer?

**Comment by jbcden** [comment]
Not sure if this is related to https://github.com/BurntSushi/rust-csv/issues/77. Is so, I would be happy to start working on the implementation!

**Comment by BurntSushi** [comment]
@jbcden Thanks for filing an issue. In general, when filing bug reports, do please take the time to provide a complete reproducible example. Otherwise, I have to guess. For example, because you didn't provide any input data, I can't tell whether "blank" means "missing field" or  "empty field."

Here's my `Cargo.toml`:

```toml
[package]
name = "csv-125"
version = "0.1.0"
authors = ["andrew <jamslam@gmail.com>"]

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
```

Here's my `src/main.rs`:

```rust
extern crate csv;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::io;

#[derive(Debug, Deserialize)]
struct Record {
    city: String,
    region: String,
    country: String,
    population: Option<u64>,
}

fn main() -> Result<(), Box<::std::error::Error>> {
    let mut rdr = csv::Reader::from_reader(io::stdin());
    for result in rdr.deserialize() {
        let record: Record = result?;
        println!("{:?}", record);
    }
    Ok(())
}
```

And here's an input file with an empty `city` field:

```
city,region,country,population
,ma,United States,10000
```

Running it, I get this output:

```
[andrew@Serval csv-125] cargo run < input.csv
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/csv-125`
Record { city: "", region: "ma", country: "United States", population: Some(10000) }
```

This is expected output, since the field is present, but empty.

Here's another CSV file, where the `city` field is missing:

```
region,country,population
ma,United States,10000
```

Running this, I get:

```
[andrew@Serval csv-125] cargo run < input.csv
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/csv-125`
Error: Error(Deserialize { pos: Some(Position { byte: 26, line: 2, record: 1 }), err: DeserializeError { field: None, kind: Message("missing field `city`") } })
```

This error is expected, since my type requires the field to exist, but it does not.

If I change my type to make the field optional, like so:

```rust
#[derive(Debug, Deserialize)]
struct Record {
    city: Option<String>,
    region: String,
    country: String,
    population: Option<u64>,
}
```

and re-run my program

```
[andrew@Serval csv-125] cargo run < input.csv
   Compiling csv-125 v0.1.0 (file:///tmp/csv-125)
    Finished dev [unoptimized + debuginfo] target(s) in 0.67s
     Running `target/debug/csv-125`
Record { city: None, region: "ma", country: "United States", population: Some(10000) }
```

then things work and `city` is populated with `None`.

If you want to **merge the notion of an empty field and a missing field**, then you can do this pretty easily, and it certainly does not require writing your own deserializer. From the [`serde` documentation](https://serde.rs/field-attrs.html#serdedeserializewith--path), you can override how a particular field is deserialized with a function using the `deserialize_with` attribute. Here is one such function that treats empty strings as errors:

```rust
fn deser_non_empty_string<'de, D>(
    de: D,
) -> Result<String, D::Error>
where D: Deserializer<'de>
{
    let s = String::deserialize(de)?;
    if s.is_empty() {
        Err(D::Error::custom("empty field"))
    } else {
        Ok(s)
    }
}
```

Here's the full program updated with the function above, along with the new `use` statements and the `serde(deserialize_with = "...")` annotation:

```rust
extern crate csv;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::io;

use serde::de::{Deserialize, Deserializer, Error};

#[derive(Debug, Deserialize)]
struct Record {
    #[serde(deserialize_with = "deser_non_empty_string")]
    city: String,
    region: String,
    country: String,
    population: Option<u64>,
}

fn deser_non_empty_string<'de, D>(
    de: D,
) -> Result<String, D::Error>
where D: Deserializer<'de>
{
    let s = String::deserialize(de)?;
    if s.is_empty() {
        Err(D::Error::custom("empty field"))
    } else {
        Ok(s)
    }
}

fn main() -> Result<(), Box<::std::error::Error>> {
    let mut rdr = csv::Reader::from_reader(io::stdin());
    for result in rdr.deserialize() {
        let record: Record = result?;
        println!("{:?}", record);
    }
    Ok(())
}
```

Here's our CSV data with an empty `city` field:

```
city,region,country,population
,ma,United States,10000
```

And running the program yields an error, as requested:

```
[andrew@Serval csv-125] cargo run < input.csv
   Compiling csv-125 v0.1.0 (file:///tmp/csv-125)
    Finished dev [unoptimized + debuginfo] target(s) in 0.65s
     Running `target/debug/csv-125`
Error: Error(Deserialize { pos: Some(Position { byte: 31, line: 2, record: 1 }), err: DeserializeError { field: None, kind: Message("empty field") } })
```

In general, CSV is not rich enough to encode the kind of constraint you want such that this library could actually form an opinion on it. Fields that are present are present, but empty. If an empty value for the type you're deserializing into is valid, then deserialization will succeed. This is the case for `String` but not, for example, for `u64`. If you want to impose additional constraints, then **serde makes this easy to do**, as demonstrated above. I do not think it is reasonable to expect the `csv` library to change its position on this, and I would instead encourage you to think about all possible uses of CSV instead of just your own.

> Not sure if this is related to #77. Is so, I would be happy to start working on the implementation!

It's not. #77 is about strictly enforcing a particular CSV format such that there exists an invalid parse. This is far below the type directed deserialization infrastructure and is instead about tweaking the CSV parser itself.

**Comment by jbcden** [comment]
@BurntSushi So sorry for not providing an example! Your example using `deserialize_with` is exactly what I was looking for, thank you so much for the very detailed response!
