### ISSUE TITLE
Zero byte read_field reads

### ISSUE THREAD

**Issue by michael-grunder** [BurntSushi/rust-csv#132]
I'm working on converting an internal tool we use from C (libcsv) into Rust and ran into something odd.  I'm new to Rust and will be unsurprised if I just don't know what I'm doing.

Here is a function I created to familiarize myself with the library:
```rust
fn stream_csv<R: Read>(infile: R) -> usize {
    let mut rdr = Reader::new();
    let mut br = std::io::BufReader::new(infile);
    let mut field = [0; 4096];
    let mut rows = 0;

    loop {
        let length = {
            let buffer = br.fill_buf().unwrap();
            let mut pos = 0;

            loop {
                let (result, nread, _nwrite) = rdr.read_field(&buffer[pos..], &mut field);
                pos += nread;

                match result {
                    ReadFieldResult::InputEmpty | ReadFieldResult::End => break,
                    ReadFieldResult::OutputFull => panic!("Output too big!"),
                    ReadFieldResult::Field { record_end } => {
                        // Is it correct to add this logic or am I doing
                        // something wrong here? :)
                        if nread > 0 {
                            if record_end {
                                rows += 1;
                            }
                        }
                    }
                }

            }

            pos
        };
        if length == 0 { break; }
        br.consume(length);
    }

    rows
}
```

This works but I had to add the `if nread > 0` logic or I will occasionally get a few extra rows reported.  Is that intended or am I implementing this streaming reader logic incorrectly in rust?

Thanks for writing this library, it's awesome!

**Comment by BurntSushi** [comment]
Thanks for filing a ticket!

In general, when filing issues, it is generally a good idea to include a minimal reproducible example. Can you provide a program and an input, show the output you get and then show the output you expect? Otherwise, it's pretty hard for me to debug and I wind up having to "guess" what you mean, which isn't really fair to me.

Also, would you mind sharing the reasons for using `csv-core` instead of `csv` itself? `csv-core`'s API is baroque, but only because it was designed to support `no_std` environments and therefore does no allocation. However, if you're using the standard library anyway, then I'm pretty sure you should be using `csv` and not `csv-core`.

**Comment by michael-grunder** [comment]
Sorry for not posting a complete example with input, but this library is so well written that I thought for sure it was something obvious that I was doing wrong or that skipping zero byte reads was the correct strategy.

First link is the full rust program and second link is input data:
https://gist.github.com/michael-grunder/20b3bd4b3a78c0339c1f62d689b11baa
https://gist.github.com/michael-grunder/9905dd5eab8ba5663b8c3b2875ff487d

The program takes a filename and whether or not to skip zero byte reads.

Here is the equivelant program using libcsv:
https://gist.github.com/michael-grunder/1f2ab1bae3449d2742d10cda831bd760

```bash
# xsv reports 1000 rows
xsv count --no-headers 1000.csv # 1000

# libcsv (from the above program) reports 1000 rows
countrows 1000.csv # 1000

# The rust program counts 1000 rows if I skip zero byte reads
# and counts 1003 rows if I do not

for n in `seq 0 1`; do cargo run --release -- 1000.csv $n; done
    Finished release [optimized] target(s) in 0.02s
     Running `target/release/phgse-rs /tmp/1000.csv 0`
Rows: 1003
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/phgse-rs /tmp/1000.csv 1`
Rows: 1000
```

I'm using csv_core directly mostly as a learning exercise.  Moving forward I want to use Rust for a lot of what I am currently doing in C and want to understand how lower level operations translate (e.g. feeding readers, etc).  I'll switch to the nicer api for this project eventually.

Cheers!
Mike

**Comment by BurntSushi** [comment]
Ah OK, that all makes sense! The reason why I needed a full example is that I don't actually use the `csv-core` API that much directly, and therefore, I don't really have an immediate intuitive grasp of what's going wrong. Once I started playing with your example, things became clearer to me. Basically, you really need to pay very close attention to the docs on [`read_field`](https://docs.rs/csv-core/0.1.4/csv_core/struct.Reader.html#method.read_field), and in particular, its termination argument. Moreover, the cases returned by [`ReadFieldResult`](https://docs.rs/csv-core/0.1.4/csv_core/enum.ReadFieldResult.html) need to be handled correctly. In particular, the **only correct way** to parse CSV data to completion with `csv-core` is to _observe the `ReadFieldResults::End` state_. In your code, you weren't actually doing that, and were instead quitting when you detected that the underlying reader had been consumed completely.

The only tweaks I needed to make were to remove your custom termination handling, and instead handle the `ReadFieldResult::End` case as the termination criterion. Another subtle detail is to be careful not to pass an empty buffer to `rdr.read_field`, since, as documented, an empty buffer is interpreted as EOF. So in this case, we break the inner loop once we'd finished reading the buffer such that the only way `read_field` is called with an empty buffer is  when there are no more bytes to read from the underlying reader.

Here's the updated code that works correctly:

```rust
extern crate csv_core;

use std::fs::File;
use std::io::BufReader;
use std::io::Read;
use csv_core::{ReadFieldResult, Reader};
use std::io::BufRead;

fn get_reader(filename: &str) -> BufReader<File> {
    let file = File::open(filename).unwrap();
    BufReader::new(file)
}

fn stream_csv<R: Read>(infile: R) -> usize {
    let mut rdr = Reader::new();
    let mut br = std::io::BufReader::new(infile);
    let mut field = [0; 4096];
    let mut rows = 0;

'LOOP:
    loop {
        let length = {
            let buffer = br.fill_buf().unwrap();
            let mut pos = 0;

            loop {
                let (result, nread, _nwrite) = rdr.read_field(&buffer[pos..], &mut field);
                pos += nread;

                match result {
                    ReadFieldResult::End => {
                        break 'LOOP;
                    }
                    ReadFieldResult::InputEmpty => {
                        break;
                    }
                    ReadFieldResult::OutputFull => {
                        panic!("Output buffer too small!");
                    }
                    ReadFieldResult::Field { record_end } => {
                        if record_end {
                            rows += 1;
                        }
                    }
                }
                if buffer[pos..].is_empty() {
                    break;
                }
            }

            pos
        };
        br.consume(length);
    }

    rows
}

fn main() -> Result<(), ()> {
    let args: Vec<_> = std::env::args().collect();
    if args.len() < 2 {
        panic!("Pass the file and whether to skip zero length field reads");
    }

    let rows = stream_csv(get_reader(&args[1]));
    println!("Rows: {}", rows);

    Ok(())
}
```

But yeah, you'll definitely want to switch to the `csv` crate. Things are much nicer there and much harder to mess up. :-)

**Comment by michael-grunder** [comment]
Ahh, that makes perfect sense thanks!  Also now I know you can do `break 'label` in rust!
