### ISSUE TITLE
Can't serialize SystemTime

### ISSUE THREAD

**Issue by nifker** [BurntSushi/rust-csv#136]
v: "1.0.2" using serde
When I try to serialize a struct that contains SystemTime I get:

"thread 'main' panicked at 'Error writing database to file '"foo.csv"': CSV write error: cannot serialize SystemTime container inside struct when writing headers from structs'"

It should serialize the Vector of Structs which contain SystemTime but fail to do so and instead panic because its unwrapping here.

example:
https://play.integer32.com/?version=stable&mode=debug&edition=2015&gist=218468a56c73bc8af9e50d1c39759cf1

**Comment by BurntSushi** [comment]
Why did you delete the issue template? Please follow the directions in the template. In particular, include a complete example that is as small as practical that reproduces the problem. Include input data, actual output and expected output.

**Comment by BurntSushi** [comment]
I don't immediately understand this bug. It will require investigation. I'm not sure when I'll have time to do that.

**Comment by BurntSushi** [comment]
For convenience, here is the code copied from the playground:

```rust
#[macro_use]
extern crate serde_derive; // 1.0.80
extern crate serde; // 1.0.80
extern crate csv; // 1.0.2

use std::path::Path;
use std::time::{SystemTime};


#[derive(Serialize, Deserialize, Clone)]
pub struct Bar{
    foo: SystemTime
    //...
    //other fields
}

pub fn serialize_bar_to_file(v: &[Bar], p: &Path) -> Result<(), std::io::Error>{
    let mut wrt = csv::Writer::from_path(p)?;

    for i in v.iter(){
        wrt.serialize(i)?;
    }

    Ok(())
}


fn main() {
    let mut v = Vec::new();
    
    v.push( Bar{ foo: SystemTime::now() } );
    
    serialize_bar_to_file(&v[..], Path::new("out.csv")).unwrap();
}
```

**Comment by alberdingk-thijm** [comment]
I've had what might be a related issue that I've been trying to understand, trying to serialize a data structure created to work with the [`Measurement`](https://docs.rs/measurements/0.10.3/measurements/trait.Measurement.html) trait from [rust-measurements](https://github.com/thejpster/rust-measurements).

I have a data structure `Price` with a single `f64` field and which implements Display using an internal macro [`implement_display!{ Price }`](https://docs.rs/measurements/0.10.3/src/measurements/measurement.rs.html#89), like so:

```rust
macro_rules! implement_display {
    ($($t:ty)*) => ($(

        impl ::std::fmt::Display for $t {
            fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
                let (unit, value) = self.get_appropriate_units();
                value.fmt(f)?;      // Value
                write!(f, "\u{00A0}{}", unit)
            }
        }
    )*)
}
```

`self.get_appropriate_units()` returns a `(&'static str, f64)` pair.

Currently, I'm getting around this issue by converting the value to a string first and then writing it. I noticed that trying that for this example with `SystemTime` doesn't work, as `SystemTime` doesn't implement `Display`, but converting it to its `Debug` representation does work.

[Here's](https://play.integer32.com/?version=stable&mode=debug&edition=2015&gist=e8ad5529aa077a3cd34215866a91141e) another Playground instance demonstrating that.

**Comment by BurntSushi** [comment]
I looked into this, and this is unfortunately expected behavior. This is simply the nature of CSV colliding with the fact that the standard [`Serialize`/`Deserialize` impl for `SystemTime`](https://github.com/serde-rs/serde/blob/bb99b31eb0a55393101f9c80cd959b3a739ad70f/serde/src/ser/impls.rs#L572-L587) uses a struct, and this example is trying to use it where a scalar value is required. The confusion I think is that `SystemTime` _looks_ like a scalar value.

Specifically, the [rules for serializing CSV values](https://docs.rs/csv/1.0.5/csv/struct.Writer.html#structs) are relevant here. Namely:

> However, if `has_headers` were enabled in the above example, then serialization would return an error. Speficially, when `has_headers` is true, there are two restrictions:
>
> 1. Named field values in structs must be scalars.
> 2. All scalars must be named field values in structs.

I think the appropriate answer to this is, "don't use `SystemTime` in CSV data." Or if you must, then you must come up with a serialization format that works inside CSV data. For a simpler work-around, consider using [`chrono`](https://docs.rs/chrono) or [`humantime`](https://docs.rs/humantime).
