### ISSUE TITLE
How to sort the results by column?

### ISSUE THREAD

**Issue by dessalines** [BurntSushi/rust-csv#143]
While it's extremely easy to sort results by column in bash, I can't figure out a way to do it with this library.

**Comment by BurntSushi** [comment]
In the future, please consider including more details with your question. In particular, please provide the things you've tried so far. Without that, it makes it very difficult for maintainers to answer your question. Please be more respectful of maintainer's time by giving as much detail as possible.

This isn't really a `csv` related question. It's a general Rust question. To sort records, you need to collect them all into memory and use [`sort_by`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by). That's it. Comparing this with bash is a bit weird, since this is a library, not a interactive programming language.

Here's a simple example:

```rust
use std::error::Error;

fn main() -> Result<(), Box<Error>> {
    let data = "\
city,country,pop
Marlborough,US,15000
Concord,US,42695
Boston,US,4628910
";

    let mut rdr = csv::Reader::from_reader(data.as_bytes());
    let mut records = rdr
        .records()
        .collect::<Result<Vec<csv::StringRecord>, csv::Error>>()?;
    records.sort_by(|r1, r2| r1[0].cmp(&r2[0]));

    let mut wtr = csv::Writer::from_writer(vec![]);
    wtr.write_record(rdr.headers()?)?;
    for r in records {
        wtr.write_record(&r)?;
    }

    let output = wtr.into_inner()?;
    let expected = "\
city,country,pop
Boston,US,4628910
Concord,US,42695
Marlborough,US,15000
";
    assert_eq!(output, expected.as_bytes());

    Ok(())
}
```

where I have

```toml
[dependencies]
csv = "1"
```

in my `Cargo.toml`.
