### ISSUE TITLE
Add typed writer

### ISSUE THREAD

**Issue by cksac** [BurntSushi/rust-csv#146]
csv::Writer serialize is allow to be called for T: Serialize and throw error at run-time if fail some checking.
e.g. `CSV error: found record with 2 fields, but the previous record has 3 fields`

but following will run without complain, 
```rust
use csv::Writer; // 1.0.5
use serde::Serialize;
use std::error::Error;
use std::io::Write;
use std::marker::PhantomData;
use std::process;

#[derive(Serialize)]
struct ProductRow {
    product_id: usize,
    warehouse_id: usize,
    iventory: usize,
}

#[derive(Serialize)]
struct OrderRow {
    order_id: usize,
    prodict_id: usize,
    qty: usize,
}

fn example() -> Result<(), Box<Error>> {
    let mut wtr = Writer::from_writer(vec![]);

    wtr.serialize(OrderRow {
        order_id: 1,
        prodict_id: 2,
        qty: 3,
    })?;

    wtr.serialize(ProductRow {
        product_id: 4,
        warehouse_id: 4,
        iventory: 100,
    })?;

    Ok(())
}

fn main() {
    if let Err(err) = example() {
        println!("error running example: {}", err);
        process::exit(1);
    }
}
```
Introduce a typed writer would catch above bug in compile time and may also offer us more opportunity to optimize when writing csv, e.g. can eliminate some of the checking when writing to W: Write.

```rust
struct TypedWriter<T, W: Write> {
    wtr: csv::Writer<W>,
    phantom: PhantomData<T>,
}

impl<T, W> TypedWriter<T, W>
where
    T: Serialize,
    W: Write,
{
    pub fn serialize(&mut self, record: T) -> csv::Result<()> {
       // TODO: can eliminate some of the checking when writing to..
        self.wtr.serialize(record)
    }
}
```

**Comment by BurntSushi** [comment]
It's a clever idea, and I do appreciate the desire for type safety here. However, I don't think it's worth the additional complexity to the API by introducing multiple different ways to serialize CSV records. Moreover, a key part of the API you left out here is the _construction_ of `TypedWriter`, which is a bit awkward, since its construction either requires writing the first record or an explicit type instantiation.

> may also offer us more opportunity to optimize when writing csv, e.g. can eliminate some of the checking when writing to W: Write.

It's a nice thought, but these checks are negligible in my experience.
