### ISSUE TITLE
Q: Access "raw" source data when a Reader is used?

### ISSUE THREAD

**Issue by mvanleeu** [BurntSushi/rust-csv#162]
### What version of the `csv` crate are you using?
1.1.1

#### Briefly describe the question, bug or feature request.
When using a source via a "from_reader" method of a ReaderBuilder , like in this example  `https://docs.rs/csv/1.1.1/csv/struct.ReaderBuilder.html#example-2` I would like to be able to access the raw slice of data used to feed each particular record in that source.

**Use case**: I parse a large CSV file to basically "grep" some of the lines based on the values of some of the fields in the CSV. 
Like "grep", I would actually need to output the matching lines in full, but found no way to access the underlying data (like "_city,country,pop_", then "_Boston,United States,4628910_", then "_Concord,United States,42695_" in the above example.

The input lines could be recreated by looping through all the fields of the matching records and use the right separators etc, via a Writer / write_record method but it would be more convenient / faster to have access to those original data.

Is it already possible somehow, or would that be a feature request?

**Comment by BurntSushi** [comment]
No, it's not possible. At no point is the original text stored like that. The CSV reader doesn't read record-by-record, because there is no way to determine how long a record is. As it reads each field from the underlying stream, it does unescaping immediately, so the full unaltered original text is never available. Making it available in the current architecture would be a significant complication and likely regress performance fairly significantly in common cases, which is certainly not worth doing to satisfy a niche case like you've presented here. (There exist alternative architectures for CSV handling that do unescaping lazily, and that architecture may be more amenable to your use case here. But it has other downsides.)

The best you can do here is to read `ByteRecord`s, search them, and then write them with [`Writer::write_byte_record`](https://docs.rs/csv/1.1.1/csv/struct.Writer.html#method.write_byte_record). It won't be as fast as you hope, but it should be faster than using `write_record`. This is how [xsv's `search` sub-command works](https://github.com/BurntSushi/xsv/blob/c0d26668a6808f564e031a00cb8bb7418dcbfd94/src/cmd/search.rs#L70-L78).
