### ISSUE TITLE
Suggestion: Readers/Writers that work with AsyncRead/AsyncWrite

### ISSUE THREAD

**Issue by rjsberry** [BurntSushi/rust-csv#171]
Hi @BurntSushi.

#141 briefly touched on this, but with the coming stabilization of async/await have you had any further thoughts on how async might integrate with the `csv` crate?

My use case is integrating CSV logging into a larger async application. At the moment I am post-processing binary files, but it would be great to work with CSV directly.

**Comment by foisonocean** [comment]
@BurntSushi 

I don't understand how `AllowStdIo` will work in this situation.

`AllowStdIo` can add `AsyncRead` implementation for something has implement `Read`, rather than adding `Read` implementation for something has implement `AsyncRead`.

 Say we have a thing has implement `AsyncRead`, and `csv::Reader::from_reader` requires implementing `Reader` trait, so we can't use `AllowStdIo` to make them work together.

Suggestions: can we have something like `csv::AsyncReader` that can be construct from a `AsyncRead` or a `Stream`, that will be very easy to use in an async context.

**Comment by BurntSushi** [comment]
@foisonocean See: https://github.com/BurntSushi/rust-csv/pull/199

**Comment by gwierzchowski** [comment]
Just wanted to mention that I have pushed [csv-async](https://crates.io/crates/csv-async) to crates.io.  
If there would be an intention to merge it to this crate (e.g. to reduce code duplication) I'm open for it.
