### ISSUE TITLE
Allow Empty Fields to Be Parsed as Default

### ISSUE THREAD

**Issue by cwfitzgerald** [BurntSushi/rust-csv#172]
#### What version of the `csv` crate are you using?

`v1.1.1`

#### Briefly describe the question, bug or feature request.

Allow empty fields to be deserialized into their field's default.

#### Example

Given the following struct:
```rust
#[derive(Deserialize)]
struct DefaultableCSV {
    a: f32,
    #[serde(default = "DefaultableCSV::b_default")]
    b: f32,
    #[serde(default = "DefaultableCSV::c_default")]
    c: f32,
}

impl DefaultableCSV {
    const fn b_default() -> f32 {
        2.0
    }
    const fn c_default() -> f32 {
        3.0
    }
}
```
using the following reader:
```rust
let csv_reader = ReaderBuilder::new()
    .comment(Some(b';'))
    .has_headers(false)
    .flexible(true)
    .trim(Trim::All)
    .from_reader(processed.as_bytes());
```

the following successfully parse:
`1, 2, 3`
`1, 2`
`1`
resulting in
```rust
DefaultableCSV {
   a: 1.0,
   b: 2.0,
   c: 3.0,
}
```
however the following fail:
`1,,`
`1,,3`
`1,2,`
etc.

For the format I am attempting to parse, it would be beneficial for those to succeed with the same result.

#### Prior Art

I don't think this is a duplicate of #166 because that, from what I can tell, is about the `flexible` option, which already works as desired.

#### But, Why????

Yeah that's basically my thought too... but the format I am parsing uses empty values as a substitute for the default value for that field. 

This is not terribly urgent, and I am willing to hack up the deserializer (on my own fork) to make this possible until we get a more robust solution in place.

**Comment by BurntSushi** [comment]
Thanks for filing an issue. In the future, when filing issues against projects like this, _please_ provide a complete reproducible program. For example, I had to spend several minutes piecing together your comment into a program I could run. In some cases, I won't have this kind of time to spend and might not respond for quite some time. I imagine such things are true for other maintainers. A few minutes might not sound like a lot, but I maintain dozens of projects and get issues filed every single day. It adds up.

This time, I wrote the program:

```rust
use serde::Deserialize;

#[derive(Clone, Debug, Deserialize)]
struct Row {
    a: f32,
    #[serde(default = "Row::b_default")]
    b: f32,
    #[serde(default = "Row::c_default")]
    c: f32,
}

impl Row {
    const fn b_default() -> f32 {
        2.0
    }
    const fn c_default() -> f32 {
        3.0
    }
}

fn main() {
    let data = "\
1, 2, 3
1, 2,
1,,
";
    let mut reader = csv::ReaderBuilder::new()
        .comment(Some(b';'))
        .has_headers(false)
        .flexible(true)
        .trim(csv::Trim::All)
        .from_reader(data.as_bytes());
    for result in reader.deserialize() {
        let row: Row = result.unwrap();
        println!("{:?}", row);
    }
}
```

With a `Cargo.toml` of:

```toml
[package]
name = "csv-172"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
serde = { version = "1", features = ["derive"] }
```

And the output:

```
$ cargo b --release && ./target/release/csv-172
   Compiling csv-172 v0.1.0 (/tmp/csv-172)
    Finished release [optimized] target(s) in 0.74s
Row { a: 1.0, b: 2.0, c: 3.0 }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Deserialize { pos: Some(Position { byte: 8, line: 2, record: 1 }), err: DeserializeError { field: Some(2), kind: ParseFloat(ParseFloatError { kind: Empty }) } })', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This is indeed expected behavior and it won't change. The reason why your first example works is because it is the only way to specify the _absence_ of a field. When you add your commas, it turns the field from _absent_ to _empty_. Since you specified that field to be a floating point number, deserialization will always fail because an empty string isn't a valid floating point number. If the deserializer didn't have this behavior, and instead treated empty fields as absent fields, then you'd just wind up messing up a different use case. That is, you might want CSV parsing to fail when you come across an empty field that you otherwise expect to have a valid floating point number.

It would be nice if you could override this behavior on a per-field basis, but I just don't see how to do that. Serde's "default" mechanism only works when the field is _absent_, not _empty_, so the CSV deserializer has to pick how to convey those semantics from the underlying CSV data.

Now, it is plausible that we could expose a option on `ReaderBuilder` that permits tweaking this behavior. That is, we might add a `empty_as_missing` option that is disabled by default, but when enabled, treats fields that are empty as missing. This would apply to _all_ parsing on that CSV data.

With all that said, another way to look at this is to say that your _data model_ isn't quite correct. That is, if your `b` or `c` fields may be absent, then arguably, they should be an `Option<f32>` instead of a `f32`. Indeed, at the level of CSV, `Option<T>` represents precisely what you want here: a field that is either _empty_ or present _and_ valid. It might look like this:

```rust
#![allow(dead_code)]

use serde::Deserialize;

#[derive(Clone, Debug, Deserialize)]
struct Row {
    a: f32,
    b: Option<f32>,
    c: Option<f32>,
}

impl Row {
    pub fn a(&self) -> f32 {
        self.a
    }

    pub fn b(&self) -> f32 {
        self.b.unwrap_or(2.0)
    }

    pub fn c(&self) -> f32 {
        self.c.unwrap_or(3.0)
    }
}

fn main() {
    let data = "\
1, 2, 3
1, 2,
1,,
";
    let mut reader = csv::ReaderBuilder::new()
        .comment(Some(b';'))
        .has_headers(false)
        .flexible(true)
        .trim(csv::Trim::All)
        .from_reader(data.as_bytes());
    for result in reader.deserialize() {
        let row: Row = result.unwrap();
        println!("{:?}", row);
    }
}
```

This is what gives me pause about accepting a PR to add a `empty_as_missing` option, because you're ideally supposed to solve this with `Option<T>`  because it more accurately describes the data you're parsing. The option might make things more convenient, but it also adds to the overall complexity for understanding how automatic deserialization works.

**Comment by cwfitzgerald** [comment]
> In the future, when filing issues against projects like this, please provide a complete reproducible program.

Definitely. Thank you for reviewing this despite that.

> A few minutes might not sound like a lot, but I maintain dozens of projects and get issues filed every single day. It adds up.

I can only imagine, thanks for the hard work for the rust community 😃!

> This is indeed expected behavior and it won't change. The reason why your first example works is because it is the only way to specify the absence of a field...

Makes sense.

> With all that said, another way to look at this is to say that your data model isn't quite correct. That is, if your b or c fields may be absent, then arguably, they should be an Option<f32> instead of a f32. Indeed, at the level of CSV, Option<T> represents precisely what you want here: a field that is either empty or present and valid.

I agree this is probably the best solution. I already have a disconnect between the _file_'s intended data model and the data model needed to _parse_ it, so I think this will be a perfectly valid solution. Additionally I already have a proc macro automatically generating proxy deserialization objects, so fields with a default should just get modified with that macro to actually be a `Option<T>` instead of a raw `T`.

Thanks for the help and the mentorship.

Closing as out of scope.
