### ISSUE TITLE
#very slow in 890000row csv

### ISSUE THREAD

**Issue by yutiansut** [BurntSushi/rust-csv#189]
this code is about 9 seconds to run

don't know why so much slow

csv: 1.1

```rust

        let mut rdr = csv::Reader::from_path("data/PTA.csv").unwrap();
        for result in rdr.deserialize() {
            let bar: t01b2::BAR = result.unwrap();
       }
```

**Comment by BurntSushi** [comment]
Thank you for filing an issue, but I really have to request that, in the future, you **please** be more considerate of other's time. You completely ignored the issue template that I wrote to help guide folks to create actionable tickets. The very beginning of the issue template specifically asks you to **show** your problem. But your ticket thus far lacks sufficient information to help you. So what I'm asking you to do is to **help me help you**. For example:

1. You have not shown a complete code sample that I can compile and run for myself. This should, at minimum, include a complete Rust source file along with your `Cargo.toml`.
2. You have not provided me with any input on which to test your program. Therefore, it is **impossible** for me to reproduce your problem.
3. You have not shown **how you are compiling and running** your program. For example, you might not be compiling your program in release mode (which has compiler optimizations). But it's impossible for me to know this because it's missing from your ticket.

Please be more considerate in the future.

**Comment by yutiansut** [comment]
sorry for that, i put my codes and data example in this [repo](https://github.com/yutiansut/test_rust_csv) @BurntSushi

**Comment by yutiansut** [comment]
this is a ci using Github Action  [Action](https://github.com/yutiansut/test_rust_csv/runs/443795265?check_suite_focus=true#step:3:61)

**Comment by BurntSushi** [comment]
Thanks. As I mentioned above, you are not compiling your code in release mode. Which means the compiler does no optimizations. This will compile your code more quickly, but generally the runtime performance of the code will be quite bad. Running your example in release mode reduces its runtime down to 314 ms for me.

This is discussed in the tutorial: https://docs.rs/csv/1.1.3/csv/tutorial/index.html#performance

**Comment by yutiansut** [comment]
it‘s my fault !! sorry~~  i'm a green hand to rust...  my release mode 500ms about   

sorry again and thanks for your patient~
