### ISSUE TITLE
Question: implementation of Deserialize is not general enough

### ISSUE THREAD

**Issue by Timmmm** [BurntSushi/rust-csv#195]
I'm trying to write a CSV parser that doesn't parse into `String`s, following the performance tutorial:

```
#[derive(Debug, Deserialize)]
struct PostcodeRecord<'a> {
...
    latitude: &'a [u8], // String because these can also be "\N" (literal '\').
    longitude: &'a [u8],
    postcode_no_space: &'a [u8],
...
}

fn read_postcodes() -> Result<HashMap<String, Option<(f64, f64)>>> {
    let file = File::open("open_postcode_geo.csv")?;
    let reader = BufReader::new(file);
    let mut rdr = csv::ReaderBuilder::new().has_headers(false).from_reader(reader);

    rdr.deserialize().map(|result| {
        let record: PostcodeRecord = result?;
        let coords = if let (Some(lon), Some(lat)) = (
            str::from_utf8(record.longitude).ok().and_then(|x| x.parse::<f64>().ok()),
            str::from_utf8(record.latitude).ok().and_then(|x| x.parse::<f64>().ok()),
        ) {
            Some((lon, lat))
        } else {
            None
        };
        Ok((str::from_utf8(record.postcode_no_space).unwrap().to_string(), coords))
    }).collect()
}
```

However this code doesn't work because I get the following error:

```
error: implementation of `_IMPL_DESERIALIZE_FOR_PostcodeRecord::_serde::Deserialize` is not general enough
   --> src/main.rs:59:23
    |
59  |       rdr.deserialize().map(|result| {
    |                         ^^^ implementation of `_IMPL_DESERIALIZE_FOR_PostcodeRecord::_serde::Deserialize` is not general enough
    | 
   ::: /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:531:1
    |
531 | / pub trait Deserialize<'de>: Sized {
532 | |     /// Deserialize this value from the given Serde deserializer.
533 | |     ///
534 | |     /// See the [Implementing `Deserialize`][impl-deserialize] section of the
...   |
569 | |     }
570 | | }
    | |_- trait `_IMPL_DESERIALIZE_FOR_PostcodeRecord::_serde::Deserialize` defined here
    |
    = note: `PostcodeRecord<'_>` must implement `_IMPL_DESERIALIZE_FOR_PostcodeRecord::_serde::Deserialize<'0>`, for any lifetime `'0`...
    = note: ...but `PostcodeRecord<'_>` actually implements `_IMPL_DESERIALIZE_FOR_PostcodeRecord::_serde::Deserialize<'1>`, for some specific lifetime `'1`
```

Any idea what this means?

**Comment by BurntSushi** [comment]
As the issue template requests, please include a **complete** program. I cannot run your code as is.

**Comment by Timmmm** [comment]
Here's a much simpler program that gives the same error:

```
use serde::Deserialize;
use std::str;

#[derive(Debug, Deserialize)]
struct TestRecord<'a> {
    x: &'a [u8],
}

fn main() {
    let data = "1\n2\n3\n";
    let mut rdr = csv::ReaderBuilder::new().has_headers(false).from_reader(data.as_bytes());

    let xs = rdr.deserialize().map(|result| {
        let record: TestRecord = result.unwrap();
        let x_int = str::from_utf8(record.x).unwrap().parse::<i32>(); // shot
        x_int
    }).collect::<Vec<_>>();
}
```

Maybe this should be on StackOverflow instead...

**Comment by BurntSushi** [comment]
Thanks for giving me a program that compiles.

Yes, you fundamentally cannot do this. I note that this does not actually correspond to the example in the tutorial. The tutorial specifically uses `read_byte_record` and then calls its [`deserialize`](https://docs.rs/csv/1.1.3/csv/struct.ByteRecord.html#method.deserialize) method.

The reason why this cannot work is because `TestRecord` is _borrowed_ from the CSV record. As soon as you move to the next iteration, the previous record evaporates. So the iterator itself cannot be constructed, otherwise it would be possible to violate memory safety.

Now in your particular case, you are not hanging on to any of the borrowed contents. Instead, you're converting it to an integer and hanging on to that. So your program is actually safe, but I don't know how to prove it to the compiler. So to do what you want, I'd recommend following the strategy in the tutorial. I mention this in the tutorial:

> The second change is a bit tricky, because in order for it to work, our Record type needs to borrow from the data inside the StringRecord. That means that our Record value cannot outlive the StringRecord that it was created from. Since we overwrite the same StringRecord on each iteration (in order to amortize allocation), that means our Record value must evaporate before the next iteration of the loop. Indeed, the compiler will enforce this!

**Comment by BurntSushi** [comment]
And yes, the error message really stinks here. Not sure how to improve on that. cc @dtolnay

**Comment by Timmmm** [comment]
Thanks for the reply! I still don't quite get why the borrow checker isn't ok with this even if I explicitly `drop(record)`, but following the approach in the tutorial worked fine.

Using this as an example next time someone tries to tell me Rust is simple! :-D

**Comment by BurntSushi** [comment]
It's because the type system isn't expressive enough to prove it. The problem is likely creating the iterator in the first place. Imagine, if, for example, you did `rdr.deserialize.collect()`. It would trivially violate memory safety. Rust doesn't really have any way of knowing that something inside your iterator made it safe because the iterator protocol itself is not expressive enough. It's plausible that Rust will some day get a kind of "streaming" iterator, but new language features (generic associated types) need to be added for that. AFAIK, it's being worked on.

> Using this as an example next time someone tries to tell me Rust is simple!

Consider that you're trying to do something that really no other language can do: simple, efficient and automatic deserialization into a custom type of your choosing with zero allocation (or, at least, amortized allocation). It's pretty awesome that you can even do this at all. The easier path, where amortizating allocation isn't done, is considerably simpler.

**Comment by Timmmm** [comment]
> The problem is likely creating the iterator in the first place. Imagine, if, for example, you did `rdr.deserialize.collect()`.

Ah yeah that makes sense, thanks!

> It's pretty awesome that you can even do this at all.

Yeah totally! I don't mind the complexity - you get awesome stuff in return. I just hate it when people pretend the complexity doesn't exist.
