### ISSUE TITLE
Guess column type from a sample 

### ISSUE THREAD

**Issue by fgadaleta** [BurntSushi/rust-csv#206]
Similarly to what Python Dask, the type of a column is defined from the first chunk. In this case, the type of the column can be determined by a sample of the elements in the column and applied after a 1st pass.

**Comment by BurntSushi** [comment]
This isn't a good fit for this crate. I would recommend building this functionality in a new crate.

That this feature exists in Python doesn't mean it can be easily ported to Rust. In particular, Python is dynamically typed.

**Comment by fgadaleta** [comment]
This has nothing to do with strongly/dynamically typed languages. This feature would make reading CSVs more robust IMHO.
If one statically defines the type of a column and makes a mistake, that column would basically be empty (or program panics).
Anyway, I guess it can be implemented somewhere else (at dataframe level or another abstraction level).
Tnx

**Comment by BurntSushi** [comment]
If you get the type wrong, then you get a deserialization error. I don't see how guessing the types at runtime would do anything to alleviate that.

But maybe you have a different feature in mind. Please consider providing more detail in feature requests you make to open source projects.

**Comment by fgadaleta** [comment]
Apologies for missing info. I am referring to cases in which I don't really know the type of a column (except if I manually investigate before parsing) and I load a csv defining the usual 
```
struct Record {
colname: <type>
}
```
My problem with that is that sometimes I don't really know what `<type>` is. I think it would be nice to have a method in the `Reader` that sets a flag like `majority_type=true` and `<type>` would be "discovered" automatically from the data (by counting how many casts to primitive types fail/succeed, with last resort to String).
Again such a functionality probably belongs to a higher lever abstraction.

**Comment by BurntSushi** [comment]
You can't do that. That's why I mentioned dynamic typed. In Rust, all types must be known statically. You can't guess the type at runtime like you can in Python. Even if you could, looking at the type in the forest row doesn't mean it will be correct for the second row, so you could still get a deserialization error.

The only way to do what you want in Rust is to create an enum, where each variant is a different primitive type. The write a serde::Deserialize impl for it that implements your guessing logic. Using such values will then require case analysis over the enum.
