### ISSUE TITLE
How do I write the csv data to a variable, so that I can send it as  a server response

### ISSUE THREAD

**Issue by asnimansari** [BurntSushi/rust-csv#216]
I would like to know, how can I generate a CSV content and store it to a variable, so that I can send it as a server response.

Can u add an example for the same ?

**Comment by BurntSushi** [comment]
I'd suggest reading the tutorial. There are lots of examples there: https://docs.rs/csv/1.1.4/csv/tutorial/index.html

Otherwise, a [`csv::Writer` can be constructed from anything that implements `std::io::Write`](https://docs.rs/csv/1.1.4/csv/struct.Writer.html#method.from_writer). Presumably, that could be a server response writer.
