### ISSUE TITLE
Iterable as multiple lines instead of one

### ISSUE THREAD

**Issue by woshilapin** [BurntSushi/rust-csv#221]
#### What version of the `csv` crate are you using?

1.1.4

#### Briefly describe the question, bug or feature request.

This is not really a bug report since the behavior is the one described [in the documentation](https://docs.rs/csv/1.1.5/csv/struct.Writer.html#structs), but I was wondering why when having a iterable of `struct` sent to `Writer::serialize()`, it doesn't create one line per `struct` instance but instead, flatten them together.

#### Include a complete program demonstrating a problem.

I would expect the following code to work.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c2264b17d46859036d7dc3456049b39a

#### What is the observed behavior of the code above?

```csv
id,name,id,name
0,Alice,1,Bob
```

#### What is the expected or desired behavior of the code above?

```csv
id,name
0,Alice
1,Bob
```

# Related issues

I noticed this behavior trying to use `insta::assert_csv_snapshot!()` (and I actually started to report a bug [there](https://github.com/mitsuhiko/insta/issues/156))

**Comment by BurntSushi** [comment]
Because `serialize` writes one record. I'm not sure why one would expect it to do otherwise. Consider what would happen if you gave it a `Vec<f64>`. Should it write one record per float? Or write a single record with each float as a distinct field? The latter seems appropriate to me.

The bottom line is that we have to make a choice and that choice has to be universal. If you wanted to serialize multiple floats in a single record, then it would be pretty hard to do that if `serialize` by default wrote each float as a separate record. In contrast, it's trivial for you to get your desired output: call `serialize` for each item.

As a meta point, I would encourage you to peruse the issue tracker for serde related issues. There are a number of them. It has been by far the biggest source of bugs and unintuitive behavior.

**Comment by woshilapin** [comment]
Thanks for the answer and the explanation, I understand the default behavior, and it does make sense. At least, this reported issue make even more explicit the decision for posterity!
