### ISSUE TITLE
Escaped quotes move to end in deserialised output, mangle next line

### ISSUE THREAD

**Issue by OJFord** [BurntSushi/rust-csv#222]
#### What version of the `csv` crate are you using?

1.1.5

#### Briefly describe the question, bug or feature request.

1. CSV data containing a field `"foo \" bar"` results in deserialised output `"foo \\ bar\""`;
1. If there is a subsequent record, the quote pairs seem to get mis-matched, resulting in an error like:
> CSV error: record 1 (line: 2, byte: 87): found record with 8 fields, but the previous record has 9 fields

#### Include a complete program demonstrating a problem.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9cd650ad83069d8dad47c89bd1917a44
```rust
use csv; // 1.1.5
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Record {
    a: String,
    b: String,
    c: String,
}

fn main() {
    println!("\nbasic repro - escaped quote moves to end of field");
    let data = r#"
"a","foo \" bar","b"
    "#;

    let mut rdr = csv::Reader::from_reader(data.trim().as_bytes());
    rdr.set_headers(csv::StringRecord::from(vec!["a","b","c"]));

    for e in rdr.deserialize() {
        let rec: Record = e.unwrap();
        println!("{:?}", rec);
    }
    
    println!("\n+comma & second line => UnequalLengths error");
    let data2 = r#"
"a","foo \", bar","b"
"c","d","e"
    "#;

    let mut rdr2 = csv::Reader::from_reader(data2.trim().as_bytes());
    rdr2.set_headers(csv::StringRecord::from(vec!["a","b","c"]));
    
    for e in rdr2.deserialize() {
        match e {
            Ok(Record{a,b,c}) => println!("{:?}", Record{a,b,c}),
            Err(e) => println!("{}", e)
        }
    }
}
```

#### What is the observed behavior of the code above?

```
basic repro - escaped quote moves to end of field
Record { a: "a", b: "foo \\ bar\"", c: "b" }

+comma & second line => UnequalLengths error
Record { a: "a", b: "foo \\", c: " bar\"" }
CSV error: record 1 (line: 2, byte: 22): found record with 3 fields, but the previous record has 4 fields
```

#### What is the expected or desired behavior of the code above?

```
// for the first:
Record { a: "a", b: "foo \" bar", c: "b" }

// second:
Record { a: "a", b: "foo \" bar", c: "b" }
Record { a: "c", b: "d", c: "e" }
```

**Comment by BurntSushi** [comment]
OK, so firstly, your example is a bit more complicated than it really needs to be. Here's a much simpler version:

```rust
fn main() {
    let data2 = r#"
"a","foo \" bar","b"
"a","foo \", bar","b"
"c","d","e"
"#;

    let mut rdr2 = csv::ReaderBuilder::new()
        .has_headers(false)
        .from_reader(data2.trim().as_bytes());
    for result in rdr2.records() {
        match result {
            Ok(record) => {
                println!("OK: {:?}", record);
            }
            Err(err) => {
                println!("ERR: {:?}", err);
            }
        }
    }
}
```

And its output:

```
OK: StringRecord(["a", "foo \\ bar\"", "b"])
ERR: Error(UnequalLengths { pos: Some(Position { byte: 21, line: 2, record: 1 }), expected_len: 3, len: 4 })
OK: StringRecord(["c", "d", "e"])
```

All right, so this is actually expected and correct behavior, although I can appreciate that it is a bit unintuitive. The second case is a bit easier to explain, so I'll start there. Here's the second row:

```
"a","foo \", bar","b"
```

So the main problem here is that CSV escapes quotes by **doubling** them, and not with the more conventional backslash. However, using a backslash is not unheard of in CSV data, which is why this crate [specifically has a feature to enable recognizing them](https://docs.rs/csv/1.1.5/csv/struct.ReaderBuilder.html#method.escape), but it is not enabled by default.

When backslash escapes are not enabled, then `"a","foo \", bar","b"` is parsed as _four_ fields: `a`, `foo \`, ` bar"` and `b`. Since this is a different number of fields from the other records in your data, the reader throws an error. However, if you enable the [flexible](https://docs.rs/csv/1.1.5/csv/struct.ReaderBuilder.html#method.flexible) option, we can squash that error and see how the reader parsed it:

```
OK: StringRecord(["a", "foo \\ bar\"", "b"])
OK: StringRecord(["a", "foo \\", " bar\"", "b"])
OK: StringRecord(["c", "d", "e"])
```

Which matches what I'd expect. Now, adjusting the code above to use backslash escapes causes the second row to be interpreted how you _want_. Specifically, the only change is in the construction of the reader:

```rust
    let mut rdr2 = csv::ReaderBuilder::new()
        .has_headers(false)
        .escape(Some(b'\\'))
        .from_reader(data2.trim().as_bytes());
```

And the output is now:

```
OK: StringRecord(["a", "foo \" bar", "b"])
OK: StringRecord(["a", "foo \", bar", "b"])
OK: StringRecord(["c", "d", "e"])
```

I note that your expected output is written as `foo \" bar`, while in my program's output it's, `foo ", bar`. My guess is that you just had a typo. Your input contains a comma inside a quoted field, so preserving it is correct.

Now, you'll _also_ notice that the first record is now also being interpreted how you want. So enabling backslash escapes fixes that problem too. Indeed, a misunderstanding of how standard CSV handles escaping is the root of this entire issue. But for completeness, why does `"foo \" bar"` parse as `foo \ bar"`? First, I'd like to note that Python has the exact same parse:

```
>>> list(csv.reader(io.StringIO(r'"foo \" bar"')))
[['foo \\ bar"']]
```

All else aside, Python's behavior served as inspiration for the behavior of this library because I perceived Python's CSV parser as likely the most widely used CSV parser in existence. If not the most, then it's at least close.

So why this behavior though? Well, the _actual_ problem is that the data as given is not actually valid CSV. Namely, since `\` isn't being treated as an escape here, the `"` after the backslash is _supposed_ to be interpreted as the end of the field. But in this case, after the end of the field, we have whitespace and alphabetic characters instead of a field delimiter (`,` in this case). If one were strictly parsing the CSV format, then this data would fail with an error at this point.

However, a design decision (again, modeled after Python's csv library) of this library is that CSV parser errors _cannot_ occur. That is, literally any input data will result in some kind of parse. While I copied this design from Python, it also makes good sense in general since CSV data is so messy. Often, it is more important to have some kind predictable parse, even for incorrect CSV data, then to cough up and refuse to handle bad data at all. In practice, CSV data is quite messy and so this ends up being a useful property.

The downside is that invalid CSV data has to be mapped to a parse somehow, and in some cases, like this one, things get weird. To understand it, we need to work our way through the state machine that implements the parser.

When we first see the `"` after the backslash, and since we are in a quoted field, we [enter the `InDoubleEscapedQuote` state](https://github.com/BurntSushi/rust-csv/blob/6623d87f413a8120b5d84f20ea27b275e500e6c6/csv-core/src/reader.rs#L1027) and _drop_ the `"`. (If we see another `"`, then we copy that to the output, which is the implementation of escaping.) Once we are in the `InDoubleEscapedQuote` state, we have [four ways to get out](https://github.com/BurntSushi/rust-csv/blob/6623d87f413a8120b5d84f20ea27b275e500e6c6/csv-core/src/reader.rs#L1035-L1044):

* See another quote, in which case, it was an escaped `"` via doubling, e.g., `""`.
* See a field delimiter, e.g., `,`.
* See a record terminator, e.g., `\n`.
* Anything else.

That "anything else" case is actually an error case! So in this case, what do we do? We have to do _something_, so in this case, we [transition to the `InField` state](https://github.com/BurntSushi/rust-csv/blob/6623d87f413a8120b5d84f20ea27b275e500e6c6/csv-core/src/reader.rs#L1016), which is the state that handles unquoted fields. Why unquoted fields? Well, because this is an error case, the general assumption is that quoting has been messed up somehow. The `InField` state will actually permit quotes as normal characters, so it is in some sense the least likely to mess up subsequent data in that field. In particular, this is why you experience the phenomenon of the quote getting "moved" to the end of the field. It actually wasn't moved. The middle quote was dropped, and since the parser moved into the unquoted field state, the final terminating quote was treated as just a normal character.

Now perhaps better behavior might be to preserve the middle `"` and remain in the quoted field state, but this will surely produce other degenerate cases. This also has the downside of being more complex to implement. In general, the important property about error cases is that they are handled consistently and predictably so that you can at least do something with them.

Of course, in this case, it's just a simple matter of enabling backslash escapes. :-)

**Comment by OJFord** [comment]
Thanks for such a detailed and thoughtful reply. 🙂 


> the main problem here is that CSV escapes quotes by doubling them, and not with the more conventional backslash. However, using a backslash is not unheard of in CSV data

Gah. I didn't even think to check - it's not 'my' data, I'm parsing the output of something else's CSV output, and guessed the `\"` would be the cause of the issue, but not that it would be because that's not a valid escape sequence! So in (my attempt at) reducing it to a test case I just assumed it should be working.

> I note that your expected output is written as foo \" bar, while in my program's output it's, foo ", bar. My guess is that you just had a typo. Your input contains a comma inside a quoted field, so preserving it is correct.

Indeed, yes, sorry. 👍🏻 

> It actually wasn't moved. The middle quote was dropped, and since the parser moved into the unquoted field state, the final terminating quote was treated as just a normal character.

Ha, yes, that makes more sense!

> Of course, in this case, it's just a simple matter of enabling backslash escapes. :-)

Many (many, many) thanks.
