### ISSUE TITLE
How can I quickly get the number of lines in a CSV file?

### ISSUE THREAD

**Issue by JesseAtSZ** [BurntSushi/rust-csv#224]
How can I quickly get the number of lines in a CSV file?

**Comment by BurntSushi** [comment]
The number of lines or the number of records? They are not necessarily equivalent.

**Comment by JesseAtSZ** [comment]
> The number of lines or the number of records? They are not necessarily equivalent.

The number of records，before reading the csv.

**Comment by BurntSushi** [comment]
What? I'm sorry, but your question makes no sense to me. You have to read the data in order to count it.

**Comment by JesseAtSZ** [comment]
Thanks，I want to realize a function to show the reading progress, so I need to know the number of records in advance.

**Comment by BurntSushi** [comment]
Next time, start with that. This is a classic example of the XY problem.

Your progress meter should be measured by *bytes read*. Why? Because you should be able to query the file for its size before reading it.

This is not perfect though, since the file can be attended to in place. But it's the best you can do as far as I know.

**Comment by JesseAtSZ** [comment]
Well, thank you very much.
