### ISSUE TITLE
Reading from String, not from File?

### ISSUE THREAD

**Issue by Kiiyya** [BurntSushi/rust-csv#240]
#### What version of the `csv` crate are you using?
1.1.6

#### Briefly describe the question, bug or feature request.
I either can not find the documentation on how to read from a string, or this crate only supports reading from a file.
What if I have a web server to which you can upload CSV, and I get a string back, which I want to parse?

My feature request is to provide a `csv::from_string("...");` function, similar to how serde does it.
If that feature does exist, then I request for it to be added to the crate-root documentation as an example.

**Comment by BurntSushi** [comment]
Of course it's supported. Only being able to read from files would be nuts. Indeed, it's shown how to do it in the first example on the Reader type: https://docs.rs/csv/1.1.6/csv/struct.Reader.html#configuration

Just use `csv::Reader::from_reader(string.as_bytes())`.

**Comment by BurntSushi** [comment]
> What if I have a web server to which you can upload CSV, and I get a string back, which I want to parse?

I would expect you to get an io::Read to be honest.

**Comment by Kiiyya** [comment]
Well, I suppose I didn't read the docs thoroughly enough! Thanks!

**Comment by Kiiyya** [comment]
Hm, wait, you can't (safely) call `as_bytes()` on a UTF-8 string, bad things may happen. What if I have ą, ä, ß, ł in my CSV?

**Comment by BurntSushi** [comment]
@Kiiyya Can you show me an example?

The only difference between a `&str` and a `&[u8]` is that the former is a subset of the latter. More specifically, that it is guaranteed to be valid UTF-8. Since UTF-8 is ASCII compatible and CSV parsing only cares about the ASCII subset of bytes, there is no conflict.

> Hm, wait, you can't (safely) call as_bytes() on a UTF-8 string, bad things may happen.

There is nothing inherently bad about `string.as_bytes()`. It's possible you might use it improperly by making bad assumptions, e.g., "every character is 1 byte." But in that case, it's the _assumption_ that's bad. _Not_ the representation.

You might find the crate docs for the [`bstr` crate](https://docs.rs/bstr) to be edifying.
