### ISSUE TITLE
Feature request: Zero copy API

### ISSUE THREAD

**Issue by bestouff** [BurntSushi/rust-csv#264]
#### What version of the `csv` crate are you using?
```toml
version = "1.1.6"
```
#### Briefly describe the question, bug or feature request.

I'd like a zero-copy API

#### Include a complete program demonstrating a problem.

I'm parsing potentially big CSV files and I'd like to be able to replace copies of values found in the file (read in memory in one block or mmaped) with direct references to the data in the file.  
Pros:
- less allocations overhead
- ability to easily trace data back to the file for e.g. error reports using [`ariadne`](https://lib.rs/crates/ariadne) or [`miette`](https://lib.rs/crates/miette)

Cons:
- either the API is super-ergonomic (it returns `str` or `&[u8]`) but that means it's work only when opened with a byte/string buffer (and would need to know that), or it would return a `Range` and would always work (it would be me preferred version).

The slice version:
```rust
    let mut rdr = csv::Reader::from_reader(data_buffer);
    for result in rdr.slice_records() {
        let record = result?;
        for field in record {
            match field {
                Plain(value) => println!("value: {}", value),
                Escaped(value, _len) => println!("value: {}", rdr.unescape(value)),
            }
        }
    }
    Ok(())
```

The range version:
```rust
    let mut rdr = csv::Reader::from_reader(data_buffer);
    for result in rdr.range_records() {
        let record = result?;
        for field in record {
            match field {
                Plain(range) => println!("value: {}", data_buffer[range]),
                Escaped(range, _len) => println!("value: {}", rdr.unescape(data_buffer[range])),
            }
        }
    }
    Ok(())
```
Ideally I'd like to also have an `escape_into()` method to be able to handle allocations myself when handling escaped CSV data, but in my case it's such an infrequent occurrence that an extra copy wouldn't hurt much.

**Comment by BurntSushi** [comment]
This isn't going to happen, sorry. If you truly 100% must have a zero-copy API, then you'll have to go out and build your own. It requires a completely different architecture than what is in this crate.

I'll respond in a bit more detail, because there seems to be some confusion in your comment.

> I'm parsing potentially big CSV files and I'd like to be able to replace copies of values found in the file (read in memory in one block or mmaped) with direct references to the data in the file.

Why?

> less allocations overhead

This benefit is conflating "zero-copy" with "zero-alloc." A zero-allocation API is already offered in `csv-core`. And an _amortized_ zero-allocation API is already offered in `csv` proper, which is often good enough. For example, you can re-use a `ByteRecord` to read rows into, and it will reuse its underlying allocation. Thus, in most cases, reading from the CSV data won't incur any new allocations. When using these APIs, the "allocation overhead" is in practice _zero_.

> ability to easily trace data back to the file for e.g. error reports using [`ariadne`](https://lib.rs/crates/ariadne) or [`miette`](https://lib.rs/crates/miette)

This crate already provides information that permits one to construct end user consumable error messages via the [`Position`](https://docs.rs/csv/latest/csv/struct.Position.html) type, which you can extract from `csv::Error` or even a `csv::Reader`.

> either the API is super-ergonomic (it returns `str` or `&[u8]`) but that means it's work only when opened with a byte/string buffer (and would need to know that), or it would return a `Range` and would always work (it would be me preferred version).

These are not ergonomic APIs because you're not accounting for unescaping. You do account for it in your code sample, and from the code sample, it should be clear that it's quite a bit less ergonomic than the existing API.

_Practically_ speaking, this isn't going to happen because unescaping it built into the very lowest levels of the parser in `csv-core`. (Feel free to have a look.) Therefore, providing a zero-copy API means either re-writing the parser to make this configurable in some way or writing a second parser that doesn't unescape fields. This in turn creates an API design nightmare at higher levels, to the point where most of the existing API would need to be duplicated: one half deals with the copying API and the other half deals with the zero-copy API. This is not feasible for me to maintain, and to be honest, there is little benefit of stuffing the zero-copy API into this crate. It is different enough from this crate's architecture that it can and should live in a different crate.

Theoretically speaking, I don't think you've really motivated the use of the zero-copy API well enough anyway. There seems to be an assumption in your comment that it will be faster, but this isn't totally clear to me, and seems quite data dependent. A zero-copy architecture does make the mmap use case more pleasant, but mmap can't always be used and it isn't always necessarily faster. Treating CSV data as a stream---as this crate does---is by far the most flexible and universal approach to dealing with large data. The only requirement is that any individual record can fit into memory, but this is typically quite reasonable.

**Comment by bestouff** [comment]
Oh yes there was a slight misunderstanding. The aim is not to be faster, the aim is to cut on small allocations. I'm parsing several gigabytes of data from a few big files and once the total structure is built for big designs I may reach a few hundred GB. The most efficient way to store identifiers and literals has been (by far) to use references into the files I'm loading in one block.  
Now I'd like to do the same for the CSVs that add data to the design, to keep a uniform error reporting system and continue to keep allocations low (I'm sorry I don't have my tests figures anymore, but replacing small allocations by just (optimized) slices had been a great RAM saver).  

I looked into using `csv-core` directly but it has the same problem - the parsing and conversion are intimate and you can't do one without the other. And so I've looked at the source code; okaye I understand the *practical* problems about parsing without writing; basically both of them are the same regex-like code.  
Thanks anyway for having taken the time for a detailed answer, I appreciate that.

**Comment by TomzBench** [comment]
I really like the `reader.deserialize()` api, however, it must take a `DeserializeOwned`.  So this means I can't deserialize a struct that has ` &'a str` in it?  I kinda assumed that would be OK because the data is usually in a file I just opened and I thought I could just reference it in my struct.

Personally I dont care about performance, zero copy, etc. Im sure cloning the strings would be fine. I just dont want to re-write all my data types though, since I simply `[serde(Deserialize)]` on them, and it seems I cant use them. 

Is my understanding correct?

**Comment by BurntSushi** [comment]
You can't do it with that API because the strings only exist temporarily inside the reader's internal buffer.

But there are other APIs that let you do it, and of course they come with constraints related directly to the lifetime of the reader. There's a whole section on it in the tutorial: https://docs.rs/csv/latest/csv/tutorial/index.html#serde-and-zero-allocation

**Comment by TomzBench** [comment]
Ahhh very cool. The API seems perfect this way because in a stream situation you only have access to 1 record at a time anyway. 

Thanks for help! And sorry for bumping a closed thread. I didn't think my newb question was worthy of a new issue 😅

**Comment by BurntSushi** [comment]
It's fine. I'm the future, please don't ask questions in old issues. Instead, open a Discussion question: https://github.com/BurntSushi/rust-csv/discussions
