### ISSUE TITLE
CRLF only record terminator

### ISSUE THREAD

**Issue by TrAyZeN** [BurntSushi/rust-csv#294]
Hi,

I have a CSV file with fields containing `\n` and with `\r\n` as record terminator. From what I understand from [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180) it is a valid CSV file.

I cannot read that file since `csv::Terminator::CRLF` terminates on `\r\n` but also on `\n` and `\r` which cut records. Also, `csv::Terminator::Any(u8)` only allows to specify a single character as a terminator which is not enough.

I would expect a variant (maybe named `csv::Terminator::CRLFOnly`) that terminates records only on `\r\n` or a variant that allows to specify a sequence of characters as a terminator.

**Comment by BurntSushi** [comment]
Please provide a program that reproduces the problematic behavior asking with any input, instructions to run the program, actual output and desired output.

**Comment by TrAyZeN** [comment]
Sorry about that.

Program to reproduce the problematic behavior:
```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Record {
    record_type: RecordType,
    #[serde(default)]
    title: String,
    #[serde(default)]
    description: String,
}

#[derive(Debug, Deserialize)]
enum RecordType {
    Book,
    Comics,
}

fn main() {
    let file = std::fs::File::open("books.csv").unwrap();

    let reader = csv::ReaderBuilder::new()
        .delimiter(b';')
        .has_headers(false)
        .flexible(true)
        .from_reader(std::io::BufReader::new(file));

    for record in reader.into_deserialize::<Record>() {
        println!("{:?}", record);
    }
}

```

Input file:
[books.csv](https://github.com/BurntSushi/rust-csv/files/10309956/books.csv)

Actual output:
```
Ok(Record { record_type: Comics, title: "Hello", description: "Hello world" })
Ok(Record { record_type: Book, title: "Lorem", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." })
Err(Error(Deserialize { pos: Some(Position { byte: 94, line: 3, record: 2 }), err: DeserializeError { field: None, kind: Message("unknown variant `Fusce auctor cursus ligula, vel sodales dolor pulvinar vitae.`, expected `Book` or `Comics`") } }))
```

Desired output:
```
Ok(Record { record_type: Comics, title: "Hello", description: "Hello world" })
Ok(Record { record_type: Book, title: "Lorem", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Fusce auctor cursus ligula, vel sodales dolor pulvinar vitae." })
```

**Comment by BurntSushi** [comment]
Umm... I don't know what your issue has to do with CRLF. Your CSV files does indeed have a mixture of `\r\n` and `\n` terminators, but I don't see any issue with the actual CSV parsing here. Your problem is that you're trying to deserialize `Fusce auctor cursus ligula, vel sodales dolor pulvinar vitae.` into a `RecordType`, and it isn't a valid value. **Which is what the error you're getting tells you.**

Either you're not reading the error messages and responding to them, or you've given me a code example that I can't make sense of. For example, your original comment talks about `\r\n` and `\n` and `\r` handling and how that screws up parsing. If that is indeed your actual problem, then you should be able to give me a minimal program that does not use Serde. Serde is clearly a complication to the problem of CRLF handling. If, though, Serde is required to reproduce your problem, then my conclusion is that CRLF handling has absolutely nothing to do with whatever problem you're facing.

**Comment by TrAyZeN** [comment]
My problem is that my file has fields containing `\n`. From what I understand, from the RFC, those `\n` (which does not constitute a CRLF) should be part of the fields as records are delimited by CRLF. So the description field should include the `\n` and the record should not end that `\n`.

Sorry the expected output was wrong (I mistakenly replaced the `\n` with a newline), I have updated it now. I will try to provide you an example without serde.

**Comment by BurntSushi** [comment]
Oh, I see. Now I understand. You want to parse CSV data that uses `\r\n` as a record terminator but which also has `\n` inside **unquoted** data. That is strange indeed. A very strict interpretation of RFC 4180 would probably indeed agree that what you're trying to do should be legal, but it is not a use case I'm inclined to support. And indeed, this specific case is documented (albeit not in an easily accessible place) as part of the behavior of the core CSV parser: https://docs.rs/csv-core/latest/csv_core/struct.Reader.html#rfc-4180

**Comment by TrAyZeN** [comment]
Understandable. Thank you for the fast answers :blush:
