### ISSUE TITLE
StringRecord to String without Result?

### ISSUE THREAD

**Issue by probablykasper** [BurntSushi/rust-csv#296]
This seems to be the recommended way to turn a `StringRecord` into a `String`:
```rs
fn example() -> Result<(), Box<dyn Error>> {
    let mut wtr = Writer::from_writer(vec![]);
    wtr.write_record(&["a", "b", "c"])?;
    wtr.write_record(&["x", "y", "z"])?;

    let data = String::from_utf8(wtr.into_inner()?)?;
    assert_eq!(data, "a,b,c\nx,y,z\n");
    Ok(())
}
```

Would it be possible to convert directly into a `String` instead of a `Result`?

**Comment by BurntSushi** [comment]
Your question and your code do not appear to be in sync. I do not see any `StringRecord` in your code.

Please clarify your question. Please also describe the high level problem you're trying to solve.

**Comment by probablykasper** [comment]
Sorry, had taken the example from [`write_record`](https://docs.rs/csv/latest/csv/struct.Writer.html#method.write_record). Hope this shows what I was pointing to:
```rs
use std::error::Error;
use csv::{Writer, StringRecord};

fn record_to_string() -> Result<String, Box<dyn Error>> {
    let record = StringRecord::from(vec!["a", "b", "c"]);
    let mut wtr = Writer::from_writer(vec![]);
    wtr.write_record(&record)?;
    
    let s = String::from_utf8(wtr.into_inner()?)?;
    Ok(s)
}
```

**Comment by BurntSushi** [comment]
> without any errors that need to be handled

Again, *why*? This isn't a problem in and of itself. You aren't describing the actual problem you're trying to solve.

**Comment by BurntSushi** [comment]
Also, once again, your question is oddly specified. If `sr` is a `StringRecord`, then `sr.as_slice().to_string()` converts it to a `String` and there is no Result there.

But judging by your code sample, this also isn't what you want.

Your problem is underspecified and I have no idea what you're trying to do.

**Comment by probablykasper** [comment]
> If `sr` is a `StringRecord`, then `sr.as_slice().to_string()` converts it to a `String` and there is no Result there.

Thank you, that's exactly what I was looking for! I couldn't find that in the docs when I was looking

The code example was the only way I had found to convert it into a string, sorry for that being confusing

**Comment by probablykasper** [comment]
Oh wait nevermind, `sr.as_slice().to_string()` doesn't include any delimiter between the fields

**Comment by BurntSushi** [comment]
I'm not responding to this issue again until you describe the ***actual problem you're trying to solve.***

I'm sorry to be harsh, but I have to protect my boundaries and I'm not going to keep going back-and-forth with you and guessing at your requirements.

**Comment by probablykasper** [comment]
My bad, I think I understand what you mean, I didn't realize you wanted to know the use case. Sorry!

I'm trying to write CSV rows individually into a `&mut String`. My code works like this at the moment:
```rs
fn write_row(writer: &mut String, sr: &StringRecord) -> Result<(), Error> {
  let mut wtr = csv::Writer::from_writer(vec![]);
  wtr.write_record(sr)?;
  // not sure if this unwrap is safe
  let record_csv_s = String::from_utf8(wtr.into_inner()?)?;
  *writer += &record_csv_s;
}
```

And I want it to function the same way, but to be infallible:
```rs
fn write_row(writer: &mut String, sr: &StringRecord) {
  let record_csv_s = ???
  *writer += &rowrecord_csv_s_s;
}
```

**Comment by probablykasper** [comment]
Thought it was more straightforward than it was, sorry for wasting your time

**Comment by BurntSushi** [comment]
That's better, but you aren't describing _why_ you want it to be infallible. I asked this question above and it has been ignored.

> Didn't realize what the word "problem" was referring to

This is a classic case of the XY problem: https://xyproblem.info/

(I wish there was a friendlier description of the XY problem, but that's the best one I know of at the moment.)

**Comment by BurntSushi** [comment]
If you want to make this specific code infallible:

```rust
fn write_row(writer: &mut String, sr: &StringRecord) -> Result<(), Error> {
  let mut wtr = csv::Writer::from_writer(vec![]);
  wtr.write_record(sr)?;
  let record_csv_s = String::from_utf8(wtr.into_inner()?)?;
  *writer += &record_csv_s;
}
```

Then I would write it like this:

```
fn write_row(writer: &mut String, sr: &StringRecord) {
  let mut wtr = csv::Writer::from_writer(vec![]);
  wtr.write_record(sr).unwrap();
  let record_csv_s = String::from_utf8(wtr.into_inner().unwrap()).unwrap();
  *writer += &record_csv_s;
}
```

I believe it is correct to say that the above code will never panic unless
you run out of memory (in which case, you'll get a hard abort), so long as
your `csv::Writer` is never configured to use non-ASCII delimiters or record
terminators. (Which it is not, of course, by default.) In particular, a CSV
writer should only return an error if given a record with unequivalent length
to prior records (unless `flexible` is enabled, which it is *not* by default),
but since you're only writing one record, this error condition can never
happen. Otherwise, I believe it is impossible for an error to be returned
unless the underlying `io::Write` implementation returns an error. But you're
here using the `io::Write` implementation for `Vec<u8>`, which will itself
never return an error (but will abort on out-of-memory).

With that said, the function, as written, seems strange to me. Writing a single
CSV record is somewhat odd. I also still question why handling a `Result` is
something you want to avoid.

**Comment by BurntSushi** [comment]
> Since there doesn't seem to be any `Writer<&mut String>`

Indeed not. `&mut String` doesn't impl `std::io::Write`.

> `unsafe { string.as_bytes_mut()}` might be another solution to it,

Yes. But oh my, please do not use `unsafe` just so you can avoid writing `unwrap`.

> I'm guessing it does since you suggested

I included a caveat.

> I'm writing an API for processing/transforming CSVs, and it only reads+writes one line at a time.

This is the *first* time you've mentioned anything resembling the actual problem you're trying to solve. Your actual problem is not "convert a string record to a string in csv format." That is a *solution* to a problem that you have kept hidden in this issue, and have only now just hinted at what it actually is.

**Why are you dealing with one record at a time by creating a new csv writer for each record?** Why not create one writer for many records? Why not handle errors?

**Comment by probablykasper** [comment]
> > I'm writing an API for processing/transforming CSVs, and it only reads+writes one line at a time.
>
> This is the _first_ time you've mentioned anything resembling the actual problem you're trying to solve

I disagree. Writing an API for processing CSVs is yet again a solution to the actual problem I'm trying to solve. In the context of this issue, the problem is to write to a `&mut String`. There's no alternative solution to that, I either have that feature or I don't.

> **Why are you dealing with one record at a time by creating a new csv writer for each record?**

I created a writer for every record because I couldn't find another way to convert a `StringRecord` to a `String`.

> Why not create one writer for many records?

That's what I would avoid by using `Writer<&mut [u8]>`. Implementing `io::Write` for a `String` seems like it could be another solution, though still not ideal because `io::Write::write()` has to accept `&[u8]`.

Ideally it would only accept utf8.

> Why not handle errors?

I don't mind handling errors, but I prefer avoiding them when the errors don't need to exist

**Comment by BurntSushi** [comment]
What you're saying doesn't make any sense to me, and the XY problem seems to be in full force here.

If you choose to open an issue on any of my projects again, please start by explaining the high level problem you're trying to solve, an as-minimal reproduction as possible, all inputs, actual output and desired/expected output. If you don't, then I'm not going to get in a back-and-forth with you again.
