### ISSUE TITLE
A nested struct deserializer problem

### ISSUE THREAD

**Issue by wjwei-handsome** [BurntSushi/rust-csv#328]
Hi, I want to deserialize a duplicate nested structure, in this example, `Foo` has two duplicated fields: `bar1` and `bar2`, they are both `Bar`.

When I run the bellow code, I just got  a Err:

`Error(Deserialize { pos: Some(Position { byte: 0, line: 1, record: 0 }), err: DeserializeError { field: None, kind: Message("invalid type: sequence, expected struct Foo") } })`

```rust
use serde::{Serialize, Deserialize};


#[derive(Serialize, Debug, Deserialize)]
struct Foo {
    #[serde(flatten)]
    bar1: Bar,
    #[serde(flatten)]
    bar2: Bar,
}

#[derive(Serialize, Debug, Deserialize)]
struct Bar {
    a: String,
    b: String,
}

fn main() {
    let csv_ = "a,b,a,b\nq,w,e,r\n";
    let f :Foo = csv::ReaderBuilder::new()
        .has_headers(false)
        .from_reader(csv_.as_bytes())
	    .deserialize().next().unwrap().unwrap();
	println!("{:?}", f)
}
```

So I want to get some advices about this.
Thanks!

**Comment by BurntSushi** [comment]
I spent about 10 minutes looking into this, and I can't make heads or tails of it myself. I note, for example, that this works:

```rust
#[derive(Serialize, Debug, Deserialize)]
struct Foo {
    a: String,
    b: String,
    c: String,
    d: String,
}
```

So to me, the `serde(flatten)` example you have should also work since it should be equivalent to the above.

If you look at the issues on this tracker, a lot of them are about Serde. And of those issues, a lot of thoses are about `serde(flatten)`. It is really one of the worst things about maintaining this library.

**Comment by BurntSushi** [comment]
I also note that this works:

```rust
use serde::{Serialize, Deserialize};

#[derive(Serialize, Debug, Deserialize)]
struct Foo {
    #[serde(flatten)]
    bar1: Bar,
    #[serde(flatten)]
    bar2: Bar2,
}

#[derive(Serialize, Debug, Deserialize)]
struct Bar {
    a: String,
    b: String,
}

#[derive(Serialize, Debug, Deserialize)]
struct Bar2 {
    c: String,
    d: String,
}

fn main() {
    let csv_ = "a,b,c,d\nw,x,y,z\nq,w,e,r\n";
    let f :Foo = csv::ReaderBuilder::new()
        .from_reader(csv_.as_bytes())
	    .deserialize().next().unwrap().unwrap();
	println!("{:?}", f)
}
```

So there is likely something funny going on with the support for Serde without header names. Since you're duplicating a struct here, I suspect what you want to do is either not possible or requires work on the Serde deserializer in this crate to make it work. (And I'm not even sure the latter is possible.)
