### ISSUE TITLE
Optional Fields

### ISSUE THREAD

**Issue by bfrog** [BurntSushi/rust-csv#33]
So I was attempting to use rust-csv to directly read in GTFS data, which is a bunch of csv files with headers. The CSV files may optionally have some fields however, and when they are there I should read them, when they are not, I should be able to skip them.

I didn't see any way to do that with rust-csv with rustc_serialize as it stands today, it looks like I'll have to do some sort of csv -> hashmap -> struct type mapping function. It would be cool if this csv library could deal with optional fields automatically.

**Comment by BurntSushi** [comment]
Could you show some example data and describe specifically how you want to read it? I ask because "optional fields" can mean a number of different things. For example, if optional field means "the column is there but a value isn't always there," then that's easy: just use an `Option<TheTypeForWhenTheValueIsPresent>`.

**Comment by bfrog** [comment]
Certainly, so in gtfs data one file might look like...

``` csv
agency_name,agency_url,agency_timezone
Chicago Transit Authority,http://www.cta.com,America/Chicago
```

Another might look like...

``` csv
agency_id,agency_name,agency_url,agency_timezone
MTA,Metropolitan Transportation Authority,http://mta.info,America/NewYork
```

Notably the agency_id column is optional according to the GTFS spec,
https://developers.google.com/transit/gtfs/reference#agency_fields

**Comment by BurntSushi** [comment]
Hmm, yeah, that will be tricky. You'll unfortunately need to roll your own handling for that sort of thing right now, because the decoder doesn't actually take field names into account. It's purely based on order, and since that kind of optional field changes the ordering, it makes that approach not workable.

I wonder if this may be helped by serde (which is the serialization framework I'll eventually move this crate too).

Having to decode each row into a hash map would be deeply unfortunate because I imagine that will slow processing down by at least an order of magnitude.

**Comment by bfrog** [comment]
Since serde does work with json well I imagine that if you follow a similiar lead to the serde_json crate, at least as possibly an optional method of decoding given csv headers (vs the position based that your using now) it should work

**Comment by abyrd** [comment]
Hello @BurntSushi, thanks for all your work on this CSV library. I just wanted to add another voice in support of using the header row to determine the order of fields and their presence or absence. My use case is the same as @bfrog. GTFS is an increasingly common CSV-based format.
