### ISSUE TITLE
How to serialize to a byte buffer

### ISSUE THREAD

**Issue by huntc** [BurntSushi/rust-csv#349]
Is there a way to serialize to a byte buffer and then write those buffered bytes out periodically? I'm establishing my writer like this:

```rust
    let mut buffer = csv::Writer::from_writer(BufWriter::new(Vec::new()));
```

That is then passed into a map closure on a stream. I want my stream map closure to serialize the fields passed to it and then return the bytes not previously returned.

**Comment by huntc** [comment]
Adding to this, I think my issue is that I can't get a mutable ref to the underlying buffer of the CSV writer. If I could, then I could clear the underlying vector.

**Comment by BurntSushi** [comment]
The csv writer owns the buffer. It wouldn't really make sense to expose a mutable ref to it. There is into_inner though.

To be honest, I don't quite understand what you're trying to do without code. My instinct is to suggest that you provide a Write implementation that does the periodic writing.

**Comment by huntc** [comment]
Here's some code:

```rust
    let mut buffer = csv::Writer::from_writer(BytesMut::new().writer());
    let event_stream = ReceiverStream::new(gateway_events_receiver)
        .map_while(|m| m)
        .map(move |(_entity_id, event)| {
            let _ = buffer.serialize(event);
            let _ = buffer.flush();
            let bytes = buffer.get_ref().get_ref().to_vec();
            Ok::<Vec<u8>, Infallible>(bytes)
        })
```

So, I establish a CSV writer which is then moved into my Stream's mapping of events. I want the mapper to write out the bytes it has and then reset the buffer. At the moment, I can't reset the buffer so it will just grow.

**Comment by BurntSushi** [comment]
Why can't you use into_inner, clear the buffer and then rebuild the writer?

**Comment by huntc** [comment]
> Why can't you use into_inner, clear the buffer and then rebuild the writer?

So, rebuild the writer for every line in my CSV file? I could have thousands of lines; might that be inefficient?

Also, doesn't the CSV write hold state?

I've just added a PR and modified my code to use it. I think a mutable ref here is fairly consistent with other libraries, including std.

```rust
    let mut buffer = csv::Writer::from_writer(BytesMut::new().writer());
    let event_stream = ReceiverStream::new(gateway_events_receiver)
        .map_while(|m| m)
        .map(move |(_entity_id, event)| {
            let _ = buffer.serialize(event);
            let _ = buffer.flush();
            let bytes_mut = buffer.get_mut().get_mut();
            let bytes = bytes_mut.split().to_vec();
            Ok::<Vec<u8>, Infallible>(bytes)
        })
```

**Comment by huntc** [comment]
Another example using just a regular vector:

```rust
    let mut buffer = csv::Writer::from_writer(BufWriter::new(vec![]));
    let event_stream = ReceiverStream::new(gateway_events_receiver)
        .map_while(|m| m)
        .map(move |(_entity_id, event)| {
            let _ = buffer.serialize(event);
            let _ = buffer.flush();
            let underlying_bytes = buffer.get_mut().get_mut();
            let bytes = underlying_bytes.clone();
            underlying_bytes.clear();
            Ok::<Vec<u8>, Infallible>(bytes)
        })
```

**Comment by BurntSushi** [comment]
std doesn't have anything like a csv writer. The csv writer owns the buffer. If it let you mutate the buffer out from beneath it, it could mess up writing. The fact that there is no mutable ref to the underlying writer is a specific and intentional design.

What you're trying to do still seems very weird to me, and I don't get why you can't invert things here and do what you need from within a custom Write impl.

It's also not clear to me that building a new writer for each record is meaningfully slower than what you're already doing. You're already sacrificing a bunch of perf by flushing after every record and generally doing things one record at a time.

I'm not 100% opposed to adding a mutable ref to the underlying writer, but I need to understand the use case much better before I can be convinced. That means explaining the higher level problem you're trying to solve and a real minimal code sample I can actually run myself.

**Comment by huntc** [comment]
> std doesn't have anything like a csv writer. The csv writer owns the buffer. If it let you mutate the buffer out from beneath it, it could mess up writing. The fact that there is no mutable ref to the underlying writer is a specific and intentional design.
> 

The parallel I'd make here is with std's `BufWriter`. `BufWriter` owns the underlying vector. However, you can `get_ref` and `get_mut` with it.

> What you're trying to do still seems very weird to me, and I don't get why you can't invert things here and do what you need from within a custom Write impl.
> 

I could write a custom writer and have `flush` clear the buffer. Perhaps that's my next move. It seems like a lot of effort though to support the use case of using this crate with a stream.

> It's also not clear to me that building a new writer for each record is meaningfully slower than what you're already doing. You're already sacrificing a bunch of perf by flushing after every record and generally doing things one record at a time.
> 

Wouldn't building a new writer for each record invoke the builder's `build` method? This appears to do a bit more than what I'm proposing.

> I'm not 100% opposed to adding a mutable ref to the underlying writer, but I need to understand the use case much better before I can be convinced. That means explaining the higher level problem you're trying to solve and a real minimal code sample I can actually run myself.

Thanks for your consideration. My higher-level requirement is that I wish to use this crate to serialize my Serde-based struct to CSV using a stream. I've no code that I can share presently. Perhaps you can describe an alternative approach to streaming out the writes with this crate.

**Comment by BurntSushi** [comment]
> The parallel I'd make here is with std's BufWriter. BufWriter owns the underlying vector. However, you can get_ref and get_mut with it.

No, that isn't a parallel. `BufWriter` isn't serializing a particular format. There's a lot less that can go wrong if you mess with the underlying writer in `BufWriter`.

> to support the use case of using this crate with a stream

I cannot believe that the right path forward here for supporting a stream is to do things one record at a time. This is why I need to understand the use case better. If you're wedged into a one-record-at-a-time handling, then either something has gone wrong or you're in a rather niche use case.

> My higher-level requirement is that I wish to use this crate to serialize my Serde-based struct to CSV using a stream.

Then you need to get more specific because this is already supported out of the box. `std::io::Write` _is_ a stream. [This example](https://docs.rs/csv/latest/csv/cookbook/index.html#writing-with-serde) is using serde to _stream_ records to stdout.

> I've no code that I can share presently. Perhaps you can describe an alternative approach to streaming out the writes with this crate.

No. I need code from you. For example, this crate does streaming already via `std::io::Write`. But you seem to be using a more specific definition of "streaming." I don't know what that is. I need code and I need a higher level description of the problem you're trying to solve. "I want to stream writes" is nowhere near specific enough.

Not being able to share the code you're actually working on is fine. I wouldn't expect that anyway because it's likely way too big for me to understand anyway. You'll need to provide some minimal reproduction of the problem you're facing.

**Comment by BurntSushi** [comment]
> Wouldn't building a new writer for each record invoke the builder's `build` method? This appears to do a bit more than what I'm proposing.

Yes. But like I said, the approach you're already using has forfeited a substantial amount of perf already. I absolutely accept that building a new CSV writer can be costly, but it's not clear to me that it matters for your use case given that you're already leaving a lot of perf on the table.

**Comment by huntc** [comment]
> I cannot believe that the right path forward here for supporting a stream is to do things one record at a time.

I’m receiving records via a channel. A stream is formed around this channel receiver. I then serialise each record. Axum then responds with this stream as the body of an http response.

**Comment by huntc** [comment]
BTW the “streaming” I’m referring to here is as described by https://rust-lang.github.io/async-book/05_streams/01_chapter.html.

**Comment by BurntSushi** [comment]
OK, thanks. I still don't understand enough about your use case to be convinced enough to add the new APIs you're requesting.

**Comment by huntc** [comment]
Here is an example with some explanation of how it can be used. The example leverages my PR.

https://github.com/huntc/test-csv-mut-ref/

**Comment by huntc** [comment]
Hey Andrew. Any further thoughts given my example? Thanks.

**Comment by huntc** [comment]
In hindsight, I'm going to close this issue and drop my PR. Given https://github.com/BurntSushi/rust-csv/issues/141, and my own usage, I now realise that rust-csv is unsuitable for working with async streams in particular (for reading as well as writing). I'll pursue my own parsing and formatting. Thanks.

**Comment by Ten0** [comment]
I have a use-case where I need to async stream a csv as a result of an async call, and because all rust web servers are async I'd like ~the same api as the issue proposes.

I find the provided example compelling. 

> There's a lot less that can go wrong if you mess with the underlying writer in BufWriter. 

It looks like we can address this concern by flushing before providing the mutable ref, like `into_inner`. Am I mistaken?

(That being said I have [the same API on an Avro writer](https://docs.rs/serde_avro_fast/latest/serde_avro_fast/object_container_file_encoding/struct.Writer.html#method.inner_mut) and don't find it error prone to use.)

> I now realise that rust-csv is unsuitable for working with async streams in particular (for reading as well as writing) 

I don't care about reading `csv`s asynchronously.
It looks to me like this method is essentially all that's needed for async write. Am I mistaken? Otherwise, could we reopen?

Thanks!
