### ISSUE TITLE
Encoding in CP Windows 1250

### ISSUE THREAD

**Issue by zszep** [BurntSushi/rust-csv#362]
Is it possible to write to file in an encoding that is not UTF8, e.g. CP Windows 1250? If yes, an example would greatly help.

**Comment by BurntSushi** [comment]
Encoding isn't the job of this crate. You'll want to use some other crate for that.

The state of encoding in Rust is not great. There is the `encoding` crate, but it's clearly abandoned. There is the `encoding_rs` crate, and it even seems to support [Windows 1250](https://docs.rs/encoding_rs/latest/encoding_rs/static.WINDOWS_1250.html), but: 1) I can't remember when it will support encoding _to_  Windows 1250, 2) its primary focus is the Encoding Standard in the context of the web, and is thus not a general purpose encoding library and 3) its API sprawling and complex. That is, `encoding_rs` doesn't have much in the way of a higher level convenience API that just does what you want for most cases.

If I were you, I'd consider hand-rolling it. Otherwise, you'll have better luck asking on a general help forum.

**Comment by zszep** [comment]
The problem I have is when importing the CSV file to Excel it defaults to CP Windows 1250 for Croatia, but I see your point. I'll create the CSV file in UTF-8 and then run an encoding converter on the file.
