### ISSUE TITLE
Feature Request: DictReader DictWriter like python

### ISSUE THREAD

**Issue by aniljava** [BurntSushi/rust-csv#56]
Rust newbie here. Please point if i missed it in documentation or there is a preferred way of achieving python's DictReader DictWriter behavior if available. If not, is this something that can be added to lib.

**Comment by BurntSushi** [comment]
My general recommendation here is to declare a struct with fields in correspondence to the fields in your CSV file. You can then decode your CSV data into structs. You can see an example here: https://github.com/BurntSushi/rust-csv/blob/master/examples/nfl_plays.rs --- You can also do this for writing too.

This isn't precisely the same as `DictReader` since decoding doesn't happen based on the name of a struct field, but rather, its position.

This library could expose an iterator that creates a `HashMap` for every row---which would be a straight-forward translation of Python's `DictReader`---but I contend that this isn't really a good fit for Rust because it would encourage writing very slow code.

It would be more helpful if you described the problem you're trying to solve instead of asking for feature X from ecosystem Y. Otherwise, all I can do is ask if you can use struct decoding like in the example, but I don't actually know if it works for your use case because I don't know what problem you're trying to solve.

**Comment by aniljava** [comment]
Thank you for your response.
I was trying to learn rust by converting existing python scripts to rust. Basically day to day scripts most of which are for one time use. 

One particular class of example where i missed the DictReader/DictWriter functionality is processing csv that was generated from document database (variable number of fields but without nesting), and to make matter tedious the the order of fields are not fixed. 

I do not have strong opinion against your second last paragraph or proper grasp of rust's type system to make sure if am right below.
1. Use cases like scripts, where extra cost in run time is acceptable compared to extra time in coding. Here defining the data contract as traits or zipping headers with records are looks like recurring boilerplate.
2. Instead of making a HashMap for every record, if `record.get("fieldname").unwrap()` [1] or `record.as_map().unwrap()` would be possible without affecting performance of the normal usage.
 
[1] https://git-wip-us.apache.org/repos/asf?p=commons-csv.git;a=blob;f=src/main/java/org/apache/commons/csv/CSVRecord.java;h=d2cbe6ac037c24268b90011c2c969ff3a1017c5d;hb=HEAD#l97
