### ISSUE TITLE
Single column CSV is unparseable

### ISSUE THREAD

**Issue by sztosz** [BurntSushi/rust-csv#70]
Hi, according to RFC 4180 a csv file that has one column without commas on the end is valid CSV file.

But how can I make reader read such file? Reader needs delimiter or defaults to `b','`, how can I pass there no delimiter? 

It's a freaking edge case, thats drives me mad :/

**Comment by BurntSushi** [comment]
@sztosz I need more details please. Can you show some sample data? Can you show some code that you've already tried? What happened? What did you expect to happen?

**Comment by sztosz** [comment]
I was able to narrow down the issue. It's all about optional column, and I think I have to just pre-parse the file before giving it to csv parser. If I have a struct
```
pub struct Row {
    pub mandatory: String,
    pub option: Option<String>
}
```
and CSV like this
```
something
anything
else
whatever
```
it won't get parsed properly, and I'll get `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Decode("Struct \'Row\' has 2 fields but current record has 1 fields.")'`
But if my CSV looks like this:
```
something,
anything,
else,
whatever,
```
It will get parsed properly.

Complete example: https://gist.github.com/sztosz/ceb4ab5c1a37b7dbdf202c143996cbae that will work or error out with csv files like those above examples.

**Comment by BurntSushi** [comment]
This is expected behavior. By deserializing into the `Row` struct, you're asking to deserialize rows with two columns. The `Option<String>` means that the second column might be empty or invalid, but the second column must still exist. Consider, for example, how the following type might be deserialized into if it were any other way:

```rust
struct Row {
    mandatory: String,
    option: Option<String>,
    mandatory2: String,
}
```

Should a record of length 2 fill in `mandatory` and `option` and therefore error when it can't fill in `mandatory2`? I think so, yes. But if we adapted to the semantics you want here, deserialization would need to account for the `option` field to be completely missing---not just empty---so that `Row` works with both 2 column and 3 column rows.

The bottom line is that structs are effectively like tuples, and tuples have a fixed arity. They expect a certain number of columns, full stop.

With that said, in the next version of the CSV crate, you can pretty much get what you want if you deserialize based on header name, which requires your CSV data to have headers. For example:

```rust
extern crate csv;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::io;

#[derive(Debug, Deserialize)]
struct Row {
    mandatory: String,
    option: Option<String>,
}

fn main() {
    let mut rdr = csv::ReaderBuilder::new()
        .flexible(true)
        .from_reader(io::stdin());
    for result in rdr.deserialize() {
        let row: Row = result.unwrap();
        println!("{:?}", row);
    }
}
```

And running it gives:

```
$ cargo run < test.csv 
Row { mandatory: "something", option: None }
Row { mandatory: "anything", option: Some("foo") }
Row { mandatory: "else", option: None }
Row { mandatory: "whatever", option: None }
```

With test data (note the header):

```
$ cat test.csv
mandatory,option
something
anything,foo
else
whatever
```

This CSV data also works:

```
$ cat test.csv
mandatory
something
anything
else
whatever
```

yields

```
$ cargo run < test.csv
Row { mandatory: "something", option: None }
Row { mandatory: "anything", option: None }
Row { mandatory: "else", option: None }
Row { mandatory: "whatever", option: None }
```

**Comment by sztosz** [comment]
Thank you for your explanation it was very helpful. The main problem was that I assumed that Option means optional column, where in fact it means, mandatory column with optional value, at least that's how i understand it. 

I dealt with my problem simply adding another one column Struct, and instead of unwrapping my `rows` I matched it, and if there was error I'm trying to read csv again to Vec of those one column structs. With Generics it's a breeze. 

I guess this Issue should be closed, because there's no problem in crate, just with me not understanding how things may and should work :)

Again, thank you very much for answer and explanation. 👍

**Comment by BurntSushi** [comment]
Sounds good. I think the next version of this crate will solve your problem. It also permits you to decode your record into a special `Record` type, which you could then deserialize into your own type in a second step based on the number of fields in the record.
