### ISSUE TITLE
Request: Optional header support for serialize nested struct

### ISSUE THREAD

**Issue by minstrel271** [BurntSushi/rust-csv#75]
May I ask if it is possible for an option to serialize struct that contains array / tuple / struct?

Previously in Python I use a flatten function to convert a nested dictionary to a flat dictionary, with field combined and seperated by some seperator (e.g. "velocity.0"), but right now serializing map or nested struct with header is not supported now.

Therefore, I would like to wish for a way to optionally serialize nested struct header with user provided seperator.

**Comment by BurntSushi** [comment]
@minstrel271 Sorry, but I don't understand your request. Could you please provide some Rust code demonstrating the feature you want and some sample output that you expect it to produce? Could you also explain more about your use case? (It would help if you divorced Python from your use case.)

**Comment by minstrel271** [comment]
Currently I need to save the list of setting and list of result as csv file. The setting contain a 2d array and the result contain 1d array. The size of the arrays are fixed in runtime, but may be changed for next build.

Current fix is to turn off has_header and insert a line of header manuelly. 

```
extern crate csv;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use std::error::Error;
use csv::WriterBuilder;

#[derive(Debug, Serialize)]
struct Setting {
    id: usize,
    connectivity: [[f32; 2]; 2],
}

#[derive(Debug)]
struct Record {
    id: usize,
    t: f32,
    state: [f32; 2],
}

fn run() -> Result<(), Box<Error>> {
    let setting = Setting {
        id: 0,
        connectivity: [[1., 0.5], [0., 1.]],
    };


    let mut wtr = WriterBuilder::new().has_headers(true).from_writer(vec![]);
    // let mut wtr = WriterBuilder::new().has_headers(false).from_writer(vec![]);
    // wtr.serialize(["id",
    //                 "connectivity.0.0",
    //                 "connectivity.0.1",
    //                 "connectivity.1.0",
    //                 "connectivity.1.1"])?;
    wtr.serialize(setting)?;


    let data = String::from_utf8(wtr.into_inner()?)?;
    assert_eq!(data,
               "id,connectivity.0.0,connectivity.0.1,connectivity.1.0,connectivity.1.1\n0,1,0.5,\
                0,1\n");
    Ok(())
}

fn main() {
    match run() {
        Ok(()) => return,
        Err(e) => println!("{:?}", e),
    }
}
```

**Comment by BurntSushi** [comment]
I'm not sure I follow. Your "fix" seems like exactly what you should be doing. How is the CSV serializer supposed to know to write headers like `connectivity.0.0`, `connectivity.0.1`, etc., automatically? That's why nested types are disallowed when writing headers, because there is an arbitrary choice that the serializer cannot make.

To clarify further: I'd really like to see the code that **you want to write**, not the code you wrote to fix your problem. I know how to fix your problem. What I don't know is what you *expect to happen*. :-)

**Comment by minstrel271** [comment]
Let me think..

```
#[derive(Debug, Clone)]
enum Key {
    Str(&'static str),
    Int(usize),
}

impl WriterBuilder {
    //...
    fn has_nested_headers(&mut self, f: Option<Box<Fn(&[Key]) -> Vec<u8>>>) -> &mut WriterBuilder {
        //...
    }
}
```
I think `Box<Fn>` would be prefered for not having extra type parameter on Writer, but I am not sure `&[Key]` and `Vec<u8>` is a suitable choice.

Usage:
```
use std::error::Error;
use std::io::Write;
use itertools::Itertools;

#[derive(Debug, Serialize)]
struct Foo {
    bar: [usize; 2],
}

fn run() -> Result<(), Box<Error>> {
    let mut wtr = WriterBuilder::new().has_nested_headers(Some(Box::new(|keys| {
        keys.iter()
            .intersperse(&Key::Str("."))
            .fold(Vec::new(), |out, key| {
                match *key {
                    Key::Str(ref s) => write!(out, "{}", s).expect("this write should not panic"),
                    Key::Int(ref i) => write!(out, "{}", i).expect("this write should not panic"),
                };
                out
            })
    })));

    wtr.serialize(Foo { bar: [0, 0] })?;

    let data = String::from_utf8(wtr.into_inner()?)?;

    assert_eq!(data, "bar.0,bar.1\n0,0\n");
    Ok(())
}
```

**Comment by BurntSushi** [comment]
@minstrel271 Could you please help me understand why you think that's better than the code in your first comment?

**Comment by minstrel271** [comment]
In case like:
```
fn foo<T: Serialize, ...>(...) {}
```
It is hard to obtain both the field name and the order of the colume.

**Comment by BurntSushi** [comment]
@minstrel271 Sorry, but I don't understand.

**Comment by minstrel271** [comment]
Inside a function generic over T, It is hard to list out all the fieldname of T as &[str]

**Comment by BurntSushi** [comment]
My suggestion is to not use nested fields. There is no way I could get on board with your nested_header method. It is way too complex. It is much simpler to just define a new type.

**Comment by BurntSushi** [comment]
I'm going to close this. I still don't quite fully understand the problem that is trying to be solved here, but the suggested API additions are far too complex IMO.

**Comment by tanriol** [comment]
The `csv` crate is a useful tool for quick and dirty exploration of data in some cases. For example, I have a stream of binary records parsed into structures with `nom` and I wanted to quickly look at the records as a table. It would be very useful to actually have column headers for that purpose so that the columns are obvious and don't have to be counted.

Sure, in theory it's possible to write the headers manually... but in practice the data includes a few arrays, nested structures (`struct Timestamp { seconds: u32, microseconds: u32 }`) so I'd actually need code for generating all the column names. Furthermore, the structures can be modified as needed (for example, skip parsing some fields for now and add them later when they're actually needed), and the code generating headers can easily get out of sync with the actual structures. The natural way out is to use a custom derive or `serde`, which is exactly what `csv` can already do.

So for me it would be useful if `csv` could actually write these nested headers in any reasonable human-readable format (being able to configure the format would be nice, but not required).

Is this feature request reasonable and, if so, what are the reasonable ways of doing that? Or should I create a separate crate just for generating column names for `csv`?
